### ISSUE TITLE
[nxz export] textures missing

### ISSUE THREAD

**Issue by virgilejarrige** [cnr-isti-vclab/meshlab#1025]
Hello again,

We have tested the éexport to nxzé function of the last nightly comit on #1022, and it seems that the textures are not embedded within the nxz file.
The generated nxz file is extremely small and when we visualise it on 3D Hop it has no texture.

We tried it on both windows and mac versions, and had the same result.

If you want to try with the same object: https://seafile.unistra.fr/d/2fe7628ab52e4c099d1f/

There you will find these files:
![meshlab-nxz-export-issue](https://user-images.githubusercontent.com/67372423/123944860-d74a5d80-d99d-11eb-84b8-b323192235d7.png)

Take care,

Virgile

**Comment by pr0m1th3as** [comment]
I confirm the issue. I have loaded an obj file with texture (.mtl + .jpg sidecar files), which is displayed properly in meshlab, and exported it to nxz format with the latest nightly build (30.6.2021) on a linux machine with Ubuntu 20.04lts. The nxz file is quite small and when loaded in 3dhop, texture is missing. Unfortunately I don't have any windows box to test with nexus converter software like @virgilejarrige 

Further information (in case it helps), since I open meshlab application from terminal with ./meshlab, when exporting to nxz format it flushes the following
....
....
QFSFileEngine::map: Mapping a file beyond its size is not portable
QFSFileEngine::map: Mapping a file beyond its size is not portable
Unifying normals
QFSFileEngine::map: Mapping a file beyond its size is not portable
Saving to file /tmp/MeshLab_64bit_fp-jTmacP/scapula.nxs
Textures: 0
LOG: 0 Saved Mesh /home/promitheas/WebPages/physicalanthropology/models/scapula.nxz in 4355 msec


Please, see if this can be resolved or if there is something missing from our end 

Thanks a lot,

Andreas

**Comment by alemuntoni** [comment]
Hi,

I checked the model you shared, and there is actually no bug here.
Nexus exporter is able to export only **per vertex** texture coordinates, not **per wedge** texture coordinates, and the model you shared has only per wedge texture coordinates. 
When a mesh has per vertex texture coordinates, the save dialog will enable the checkbox "TexCoord" of the vertex frame.

It seems that the nexus software automatically converts per wedge to per vertex texcoords before exporting the file. However, this is something that we cannot do in meshlab (we shouldn't modify the mesh when saving it!).
Therefore, when a mesh has only per wedge texcoords, you should first run the filter "convert PerWedge UV into PerVertex UV".

Note: when saving a nxs/nxz, you can safely uncheck the checkbox "Save texture file(s)" in the save dialog. That checkbox is meant for saving the textures as separated file, which is not necessary for nxs/nxz because the textures are embedded in the file. In fact, textures will be automatically included in the file if the "TexCoord" checkbox is enabled and checked.

Note 2: I solved a bug in the last commit that was affecting nxs/nxz saving parameters, the last nightly solves it.

**Comment by pr0m1th3as** [comment]
Hi again,

after applying the filter the export to nxz saves the texture but when visualized in 3dhop it looks very very distorted
![Screenshot from 2021-07-01 12-21-24](https://user-images.githubusercontent.com/26193357/124100369-17294780-da67-11eb-9d62-9ebc7e3b9316.png)
Any suggestions?

**Comment by alemuntoni** [comment]
I've really no idea. Texture quality value is 100 by default, therefore it can't be that...
@ponchio what do you think could it be?

**Comment by pr0m1th3as** [comment]
I used the default values for exporting to nxz. However, the terminal output after the export was:

Unifying normals
QFSFileEngine::map: Mapping a file beyond its size is not portable
Saving to file /tmp/MeshLab_64bit_fp-iaYhkN/ABH073-Scapula_L.nxs
Textures: 34
LOG: 0 Saved Mesh /home/promitheas/WebPages/physicalanthropology/models/ABH073-Scapula_L.nxz in 128228 msec
libpng warning: iCCP: known incorrect sRGB profile

do you think this libpng warning has anything to do with it?

**Comment by virgilejarrige** [comment]
Thank you for the quick answer and the fix!

On our side, under macOS and Windows it's working, and the visualisation in 3DHop is neat.... but the nxz file is HUGE !!!

The chair.nxz made by nexus converter is about 2,8 Mo
The chair2.obj.nxz made by meshlab is 17,2 Mo

Maybe the texture is not compressed correctly?

**Comment by virgilejarrige** [comment]
@pr0m1th3as I did ^^

And I tried to export into nxs (non compressed) format, the file is 20,7Mb

**Comment by pr0m1th3as** [comment]
The size difference is bit strange. In my case, the obj model 29.6MB + 5.5MB (jpg and mtl files) and the nxz results to 3.3MB, whereas the uncompressed nxs is much larger at 14MB.
@virgilejarrige  If it's not much trouble, could you try converting my model on windows or mac with meshlab and with nexus converter on windows? you can download the obj+jpg+mtl files from this link
https://drive.google.com/drive/folders/1WHFONkc4HzTvH12Bkir3MtRbDXwt_FD-?usp=sharing
Thanks

**Comment by alemuntoni** [comment]
The only default parameter value we changed is the "texture quality" parameter, which we set to 100 while in the nexus software was 92 (will became 100 also there). Setting texture quality, size of the nxz becomes 7.3 mb..
@virgilejarrige are you using corto lib for compression with the nexus software?

**Comment by virgilejarrige** [comment]
Fun fact..! 

I tried with another object that is originally at 106,5Mb

After being converted into nxz by meshlab it's 30Mb and it's displaying fine on 3DHop.

![Capture d’écran 2021-07-01 à 11 57 14](https://user-images.githubusercontent.com/67372423/124105806-e1cf2a80-da63-11eb-93f2-e3209c47dd46.png)

**Comment by virgilejarrige** [comment]
@alemuntoni yes, with the corto lib
@pr0m1th3as give me a sec, i'll try that

**Comment by virgilejarrige** [comment]
@pr0m1th3as 
in meshlab macOS, when pressing the "save" button to export in nxz, meshlab crashes badly... no error message
in meshlab windows, it worked but the nxz is huge (66Mb) and the model is displaying correctly in 3DHop 
in nexus converter (windows), nxs is 13,4Mb and nxz is 1,3Mb... but in 3DHop the textures are not present for both. During converting process it says it's taking textures into account though.

**Comment by pr0m1th3as** [comment]
@virgilejarrige thanks a lot Virgile. Hopefully, this might help the maintainers to figure out what is going on.
For the time being I must find a windows box to covert the few models I need for my website's 3d gallery.

**Comment by virgilejarrige** [comment]
Glad if i can help :)

if you wish to test things or if you want to compare the 3D objects i used/exported, here's a recap:

**The chair** 
https://seafile.unistra.fr/d/2fe7628ab52e4c099d1f/ 
nexus converter: OK
meshlab windows and macOS: OK but file is big

**The skull**
https://seafile.unistra.fr/d/c8cee81d0dde498d965f/
nexus converter: not tested
meshlab windows and macOS: OK

Scapula (from @pr0m1th3as)
https://seafile.unistra.fr/d/c07513d4eb5a45aaa9c3/
nexus converter: texture missing
meshlab windows and macOS: OK, but file is big

**Comment by pr0m1th3as** [comment]
thanks for the update. It looks like there is something wrong with the way the model's raw data are parsed from meshlab to nexus converter. Unfortunately, meshlab source is too complex for me to follow. Another thing about the nexus converter is that (I think if I can remember correctly) it only parses the texture correctly from ply files instead of obj ones.

**Comment by alemuntoni** [comment]
I finally understood why files are bigger when exported using meshlab:

- texture quality is 100 by default on meshab, 92 in the exporter; 
- (minor) when a ply file has no vertex normals, they are not exported in the nxs/nxz by the nxs exporter, of course; however, in meshlab when a ply has no v normals, they are computed automatically in the mesh that is stored internally by meshlab, and therefore they are saved also into the nxs/nxz. I modified the option "Vertex normal" in the nxs/nxz exporter to be unchecked by default.

Please try the last nightly build! Just modifying the texture quality parameter to 92, size of the files should be similar to the ones generated by the nexus exporter.

@pr0m1th3as I am not able to reproduce the issue on the scapula model. Could you please try to export it with the new nightly build and tell me if the visualization problem still occurs?
 
@ponchio  are you sure that 100 should actually be the default value for texture quality? The file size increases a lot.. E.g., for the chair model:
- quality 92: 7.2 mb
- quality 100: 17.0 mb

**Comment by ponchio** [comment]
The main problem with the quality setting, is the quality of the input
texture (if jpg) is unknown.
If we re-encode a jpeg with higher quality the size does not increase but
only if we re-encode the whole image or
when cutting it into pieces we align the cut to the multiple of 8 pixels.

The actual code slicing the texture in nexus does not respect the multiple
of 8. If we did, we would preserve the original quality
with a few pixels on the border 'wasted'.

**Comment by alemuntoni** [comment]
Ok, apparently there was a misunderstanding on the possibility to export per wedge coordinates, sorry about that.

With the [last commit](https://github.com/cnr-isti-vclab/meshlab/commit/ba68ef89091ee0b06b49ba34241431b6b9c97f1f) nxs/nxz can also export per wedge texture coords, and the behaviour now is almost the same of the nxsbuild software. There is no need anymore to convert per wedge coordinates into per vertex coordinates.

The only difference between the `nxsbuild` and the meshlab nxs exporter, is the texture quality parameter, which is 92 in `nxsbuild` and 100 in meshlab. Setting it to 92 will generate nxs/nxz files with the same sizes of the ones generated with `nxsbuild`.

Please try the last build and let me know if it works fine (and in case we could close this issue)

**Comment by virgilejarrige** [comment]
As said in #1029, under Windows 10 and macOS 10.15 it's doing fine.
So if it's also working under Ubuntu, I see no reason why not closing this issue.

Thanks for the awesome work and cooperation!

Take care,

Virgile

**Comment by pr0m1th3as** [comment]
I am currently away and cannot test the latest build. I will test it on Thursday though, if you don't mind waiting a couple of days before closing the issue. Most likely it will be fine, but just in case to avoid opening another ticket. Thanks

**Comment by alemuntoni** [comment]
No problem on keeping it open!
I develop in linux therefore it should be fine, but having multiple feedbacks is always appreciated :)

**Comment by pr0m1th3as** [comment]
Hi again, sorry for the delayed reply.
I just tried to build the latest meshlab at master and it produced an error during compiling related to nexus.

`/home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:947:30: error: ‘class QString’ has no member named ‘chopped’; did you mean ‘chop’?
  QString basename = filename.chopped(4) + "_files";
                              ^~~~~~~
                              chop
/home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:998:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for(int i = 0; i < textures.size()-1; i++) {
                   ~~^~~~~~~~~~~~~~~~~~~
/home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:999:14: warning: unused variable ‘tex’ [-Wunused-variable]
     Texture &tex = textures[i];
              ^~~
/home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:1016:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < textures.size()-1; i++) {
                  ~~^~~~~~~~~~~~~~~~~~~
In file included from /home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/local_optimization/tri_edge_collapse.h:28:0,
                 from /home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/local_optimization/tri_edge_collapse_quadric.h:29,
                 from /home/promitheas/meshlab/src/external/nexus/src/nxsbuild/mesh.h:22,
                 from /home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:31:
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/edge_collapse.h: In instantiation of ‘static int vcg::tri::EdgeCollapser<TRI_MESH_TYPE, VertexPair>::Do(vcg::tri::EdgeCollapser<TRI_MESH_TYPE, VertexPair>::TriMeshType&, VertexPair&, const vcg::Point3<typename ComputeMeshType::VertexType::ScalarType>&, bool) [with TRI_MESH_TYPE = TMesh; VertexPair = vcg::tri::BasicVertexPair<TVertex>; vcg::tri::EdgeCollapser<TRI_MESH_TYPE, VertexPair>::TriMeshType = TMesh; typename ComputeMeshType::VertexType::ScalarType = float]’:
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/local_optimization/tri_edge_collapse_quadric_tex.h:717:44:   required from ‘void vcg::tri::TriEdgeCollapseQuadricTex<TriMeshType, VertexPair, MYTYPE, HelperType>::Execute(TriMeshType&, vcg::BaseParameterClass*) [with TriMeshType = TMesh; VertexPair = vcg::tri::BasicVertexPair<TVertex>; MYTYPE = MyTriEdgeCollapseQTex; HelperType = vcg::tri::QuadricTexHelper<TMesh>]’
/home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:1216:1:   required from here
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/edge_collapse.h:276:23: warning: unused variable ‘f’ [-Wunused-variable]
           FaceType  & f = *((*i).f);
                       ^
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/edge_collapse.h:305:27: warning: unused variable ‘f’ [-Wunused-variable]
               FaceType  & f = *((*i).f);
                           ^
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/edge_collapse.h: In instantiation of ‘static int vcg::tri::EdgeCollapser<TRI_MESH_TYPE, VertexPair>::Do(vcg::tri::EdgeCollapser<TRI_MESH_TYPE, VertexPair>::TriMeshType&, VertexPair&, const vcg::Point3<typename ComputeMeshType::VertexType::ScalarType>&, bool) [with TRI_MESH_TYPE = Mesh; VertexPair = vcg::tri::BasicVertexPair<AVertex>; vcg::tri::EdgeCollapser<TRI_MESH_TYPE, VertexPair>::TriMeshType = Mesh; typename ComputeMeshType::VertexType::ScalarType = float]’:
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/local_optimization/tri_edge_collapse_quadric.h:186:46:   required from ‘void vcg::tri::TriEdgeCollapseQuadric<TriMeshType, VertexPair, MYTYPE, HelperType>::Execute(TriMeshType&, vcg::BaseParameterClass*) [with TriMeshType = Mesh; VertexPair = vcg::tri::BasicVertexPair<AVertex>; MYTYPE = TriEdgeCollapse; HelperType = vcg::tri::QInfoStandard<AVertex>]’
/home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:1216:1:   required from here
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/edge_collapse.h:276:23: warning: unused variable ‘f’ [-Wunused-variable]
           FaceType  & f = *((*i).f);
                       ^
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/edge_collapse.h:305:27: warning: unused variable ‘f’ [-Wunused-variable]
               FaceType  & f = *((*i).f);
                           ^
external/nexus/src/CMakeFiles/nexus.dir/build.make:205: recipe for target 'external/nexus/src/CMakeFiles/nexus.dir/nxsbuild/nexusbuilder.cpp.o' failed
make[2]: *** [external/nexus/src/CMakeFiles/nexus.dir/nxsbuild/nexusbuilder.cpp.o] Error 1
CMakeFiles/Makefile2:803: recipe for target 'external/nexus/src/CMakeFiles/nexus.dir/all' failed
make[1]: *** [external/nexus/src/CMakeFiles/nexus.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

I tried fixing according to the compiler's suggestion (i.e. renaming "chopped" to "chop") but in vain. It procuced another error shown below. Is there something I am missing? The only difference with my previous biulds that were completed is that this one was performed in Ubuntu 18.04LTS instead of 20.24LTS. I will try it again on 20.04 once I am back home, but the OS version seems irrelevant to me. Thanks a lot.
Andreas


`/home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp: In member function ‘void NexusBuilder::save(QString)’:
/home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:947:38: error: invalid operands of types ‘void’ and ‘const char [7]’ to binary ‘operator+’
  QString basename = filename.chop(4) + "_files";
                     ~~~~~~~~~~~~~~~~~^~~~~~~~~~
/home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:998:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for(int i = 0; i < textures.size()-1; i++) {
                   ~~^~~~~~~~~~~~~~~~~~~
/home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:999:14: warning: unused variable ‘tex’ [-Wunused-variable]
     Texture &tex = textures[i];
              ^~~
/home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:1016:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < textures.size()-1; i++) {
                  ~~^~~~~~~~~~~~~~~~~~~
In file included from /home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/local_optimization/tri_edge_collapse.h:28:0,
                 from /home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/local_optimization/tri_edge_collapse_quadric.h:29,
                 from /home/promitheas/meshlab/src/external/nexus/src/nxsbuild/mesh.h:22,
                 from /home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:31:
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/edge_collapse.h: In instantiation of ‘static int vcg::tri::EdgeCollapser<TRI_MESH_TYPE, VertexPair>::Do(vcg::tri::EdgeCollapser<TRI_MESH_TYPE, VertexPair>::TriMeshType&, VertexPair&, const vcg::Point3<typename ComputeMeshType::VertexType::ScalarType>&, bool) [with TRI_MESH_TYPE = TMesh; VertexPair = vcg::tri::BasicVertexPair<TVertex>; vcg::tri::EdgeCollapser<TRI_MESH_TYPE, VertexPair>::TriMeshType = TMesh; typename ComputeMeshType::VertexType::ScalarType = float]’:
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/local_optimization/tri_edge_collapse_quadric_tex.h:717:44:   required from ‘void vcg::tri::TriEdgeCollapseQuadricTex<TriMeshType, VertexPair, MYTYPE, HelperType>::Execute(TriMeshType&, vcg::BaseParameterClass*) [with TriMeshType = TMesh; VertexPair = vcg::tri::BasicVertexPair<TVertex>; MYTYPE = MyTriEdgeCollapseQTex; HelperType = vcg::tri::QuadricTexHelper<TMesh>]’
/home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:1216:1:   required from here
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/edge_collapse.h:276:23: warning: unused variable ‘f’ [-Wunused-variable]
           FaceType  & f = *((*i).f);
                       ^
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/edge_collapse.h:305:27: warning: unused variable ‘f’ [-Wunused-variable]
               FaceType  & f = *((*i).f);
                           ^
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/edge_collapse.h: In instantiation of ‘static int vcg::tri::EdgeCollapser<TRI_MESH_TYPE, VertexPair>::Do(vcg::tri::EdgeCollapser<TRI_MESH_TYPE, VertexPair>::TriMeshType&, VertexPair&, const vcg::Point3<typename ComputeMeshType::VertexType::ScalarType>&, bool) [with TRI_MESH_TYPE = Mesh; VertexPair = vcg::tri::BasicVertexPair<AVertex>; vcg::tri::EdgeCollapser<TRI_MESH_TYPE, VertexPair>::TriMeshType = Mesh; typename ComputeMeshType::VertexType::ScalarType = float]’:
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/local_optimization/tri_edge_collapse_quadric.h:186:46:   required from ‘void vcg::tri::TriEdgeCollapseQuadric<TriMeshType, VertexPair, MYTYPE, HelperType>::Execute(TriMeshType&, vcg::BaseParameterClass*) [with TriMeshType = Mesh; VertexPair = vcg::tri::BasicVertexPair<AVertex>; MYTYPE = TriEdgeCollapse; HelperType = vcg::tri::QInfoStandard<AVertex>]’
/home/promitheas/meshlab/src/external/nexus/src/nxsbuild/nexusbuilder.cpp:1216:1:   required from here
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/edge_collapse.h:276:23: warning: unused variable ‘f’ [-Wunused-variable]
           FaceType  & f = *((*i).f);
                       ^
/home/promitheas/meshlab/src/vcglib/vcg/complex/algorithms/edge_collapse.h:305:27: warning: unused variable ‘f’ [-Wunused-variable]
               FaceType  & f = *((*i).f);
                           ^
external/nexus/src/CMakeFiles/nexus.dir/build.make:205: recipe for target 'external/nexus/src/CMakeFiles/nexus.dir/nxsbuild/nexusbuilder.cpp.o' failed
make[2]: *** [external/nexus/src/CMakeFiles/nexus.dir/nxsbuild/nexusbuilder.cpp.o] Error 1
CMakeFiles/Makefile2:803: recipe for target 'external/nexus/src/CMakeFiles/nexus.dir/all' failed
make[1]: *** [external/nexus/src/CMakeFiles/nexus.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by pr0m1th3as** [comment]
Another update.
I managed to build meshlab by using the script for building and generating AppImage, which although not generated due to 18.04 instead of 16.04, it produces a working binary found in ./meshlab-build/distrib, which I run from terminal.
Nevertheless, it does not display the option to export to nxz/nxs models as the previously successfully compiled version.
Thanks. Please let me know if there is any more info I can provide which would be helpfull

**Comment by alemuntoni** [comment]
Does the appimage generated by github actions in the last build work?

About the build errors:
- do you have qt 6.x installed? we still don't support qt 6, just qt 5.12 or 5.15 (the last two lts)
- it is possible that you did not clone recursively the repository? maybe the submodule of nexus is missing, and therefore the plugin has not been built. You can check this in the cmake log, where is printed the list of plugins that will be built.

**Comment by alemuntoni** [comment]
I think this issue can be closed, right?

**Comment by virgilejarrige** [comment]
You're right! The original problem is solved! :)
