### ISSUE TITLE
Hausdorff Distance units

### ISSUE THREAD

**Issue by mattherrmann95** [cnr-isti-vclab/meshlab#1052]
Hello! 
I'm currently using MeshLab  2021.07. I´ve been using the sampling tool "Hausdorff Distance" and it works just fine, but I couldn't find out which units the results have. Is it mm oder m? Or does it depend on your meshes? In addition I want to ask, if "max" is the HD, "mean" is the mean surface distance and "RMS" is the Root mean square distance/error?  Thank you!

**Comment by liushuya7** [comment]
"RMS" is the root-mean-square. However, oftentimes I would like to have STD instead of RMS. Does anyone know how to get the standard deviation when using "Hausdorff Distance" or "Distance from Referenced Mesh" in Meshlab?

**Comment by alemuntoni** [comment]
Distance does not have units, it depends on the input meshes.
Since the distance is computed by  sampling one of the two meshes and finding for each sample the closest point over the other mesh, min is the minimum distance between a sample and its closest point, max is the maximum, mean is the mean distance and RMS is the root mean square.
