### ISSUE TITLE
Windows version special characters vs2019 compilation

### ISSUE THREAD

**Issue by weiyu666** [cnr-isti-vclab/meshlab#1057]
Windows version special characters vs2019 compilation；The latest version 2021.7 of meshlab is used，Mainly two special characters ->setText("▼")  or  ->setText("▲") ！I think it's a coding problem。
![image](https://user-images.githubusercontent.com/22174508/128768766-258b1001-6e82-4976-8933-976d128b2096.png)

**Comment by alemuntoni** [comment]
The character that cause the fail in your system is an [utf8 character](https://www.utf8icons.com/character/9650/black-up-pointing-triangle), which should be correctly supported by recent compilers. I think the issue is more related with the locale set in your machine (it builds without any issue on windows PC with an eng-utf8 locale).
