### ISSUE TITLE
Erroneous "Mesh has no texture" error for GLTF/GLB (Windows)

### ISSUE THREAD

**Issue by eischaefer** [cnr-isti-vclab/meshlab#1082]
After importing a model from either GLTF or GLB, and attempting to apply the Quadric Edge Collapse Decimation (with texture) filter, I receive an error that states: "Mesh has no texture." However, a texture is visibly present, and indeed, toggling the Texture Coord button on/off changes the view as expected.

I am using Windows 10 (10.0.19043), Meshlab v2021.07.

(I'm rather new to MeshLab, so if I've missed something obvious, please excuse me!)

**Comment by eischaefer** [comment]
GLTF file is attached.
[zun_wine_vessel_10th_c_bce.zip](https://github.com/cnr-isti-vclab/meshlab/files/7146708/zun_wine_vessel_10th_c_bce.zip)

**Comment by alemuntoni** [comment]
Thanks for reporting! I confirm the bug in any platform.
I'll look into this!

**Comment by cignoni** [comment]
Actually it is not a bug, but a feature :D 
the reason is that the quadric error simplifier for textured meshes needs a mesg with per-wedge tex coords (per-vertex tex coords imply vertex duplication on texture seams making edge-collapse based simplification more complex) 

so it is necessary to convert (with the appropriate filter) texture representation from per-vertex to per-wedge 

We will explain this in the error message 

Thanks for the bug report!
