### ISSUE TITLE
'Check for writable folder in Screened Poisson' breaks linux compatibility.

### ISSUE THREAD

**Issue by bartoszek** [cnr-isti-vclab/meshlab#110]
fb79c65  commit breaks 'poisson reconstruction' plugin on my linux system.
I'm always getting the error message. It seams that condition `fi.isWritable()` is always false (is it even feasible to check permissions of non-existing file ? `strace` showing no instance of  `file.tmp` access).
Revoking this commit fixes the issue ( _poisson-recon works fine up to octree-depht 11 on meshes with ~10^6 verts_ ).
`my system : linux-arch`
`meshlab verssion : current-git`

**Comment by mcallieri** [comment]
I will check it. I tested it on Windows, and the QT documentation did not mention any compatibility issue.. 
I was surprised too in the way QT does it... The function does not work on a directory, but on a file, It looks like it is asking "can I write this (still non-existing) file here?" instead of "is this directory write-enabled?"

**Comment by mcallieri** [comment]
actually, with a more careful search, I found many people complaining the results of that checking mechanism. The simplest and more portable solutions seems to be directly trying to create a temporary file. If the "open" returns true, then the folder is writeble

```
	QTemporaryFile file("./_tmp_XXXXXX.tmp");
	if (!file.open()) 
	{
```

the QTemporaryFile is used because it automatically change its name to avoid conflicts, and the file is automatically deleted afterwards

try it....

**Comment by bartoszek** [comment]
@mcallieri Works fine here - consider fixed.
