### ISSUE TITLE
Filter Screened Poisson not find

### ISSUE THREAD

**Issue by fillomanera** [cnr-isti-vclab/meshlab#1119]
Good morning, 

I use point clouds coming from laser scanners , some time is useful for me to build meshes to print in 3D. I would use Meshlab to do the job, but I have these two problems:

A)Op. System:  windows 7 on a pc :
I installed 2021.7 but the application seems to be not able to find some filters , expecially the screened_poisson filter,
I disinstalled the 2021.7 and installed 2021.7d : same problem
The same for the2021.05 and 2020.nn versions 
 
![meshlab2021_07d](https://user-images.githubusercontent.com/92453176/137291979-e158f533-5fd9-49cb-91cd-802dd530a508.jpg).
Probably a problem on my pc , but how to fix it?

B) op. system windows 10 on a pc: installed 2020.12: the screened_poisson exists . I works well to mesh a a cloud ( only one), but when I want to use all the visible clouds it builds a mesh with 0 faces. Flattening the clouds produces a 0 points cloud and the loss of the points in the original clouds .

do you have some idea about this ?
  
Thank you ,

Franco

**Comment by alemuntoni** [comment]
A) be sure to install correctly the [vc redist package](https://aka.ms/vs/16/release/vc_redist.x64.exe) in your pc.
B) 2020.12 is an almost one year old version. Please try the latest 2021.07 version, and if the problem persists please share the input file and all the steps that you perform in order to help us reproducing the issue.
