### ISSUE TITLE
Large VRML file not opening

### ISSUE THREAD

**Issue by consolecwby** [cnr-isti-vclab/meshlab#113]
Trying to convert VRML 2.0 file to stl. 
Part fails to load after about 25% loaded.

[TEST.zip](https://github.com/cnr-isti-vclab/meshlab/files/851136/TEST.zip)

**Comment by mcallieri** [comment]
I'm trying opening it also with other tools, but it does not seem to work. Blender is stuck after 20 minutes, and 3D-Coat gave me an "out of memory" exception.
Looking inside the file, as far as I can see, each face is a SEPARATE ENTITY, and this may be what is causing problems.
Try to see if there are options in the exporter to get a more compact representation, otherwise, why using VRML? since it is just geometry, OBJ may be better.

**Comment by consolecwby** [comment]
I work with CATIA which generates some simulation results in a proprietary .cgr file. This is the only open file that i can convert it to.

**Comment by mcallieri** [comment]
update, it took 45 minutes in Blender, and each face is converted in a scene object, which makes the software unresponsive. 
If there is an option to export all the faces int he same entity, it could work.

**Comment by mcallieri** [comment]
MeshLab opened it, it just needed 18GB of RAM... 
Due to the replication, the object has 247 MILLION vertices (each entity includes the whole set of points, as the vertex group is referenced in each entity)
See if there are exporting parameters, or write an obj exporter as a script... it's easy

![clipboard-1](https://cloud.githubusercontent.com/assets/12409141/24054653/3c9389ca-0b3d-11e7-8de8-19797700b3f9.jpg)

**Comment by mcallieri** [comment]
here is it, after removing the replication. but it took ages.
[export.zip](https://github.com/cnr-isti-vclab/meshlab/files/851331/export.zip)
