### ISSUE TITLE
Feature Request - Take snapshot from command line

### ISSUE THREAD

**Issue by nyersa** [cnr-isti-vclab/meshlab#119]
Can we have a way to take a snapshot of a mesh using meshlabserver? I am running a script on a large amount of meshes would like to be able to generate thumbnails of the output.

**Comment by cignoni** [comment]
Done in commit 928f36139df396dfe3497430d5046849dc3fe21f 
 (could be improved but the basic stuff is there...)

**Comment by Jarett-Lee** [comment]
Hello, I looked through the commit as closely as I could to figure out how to take a snapshot using meshlabserver, but I couldn't find the change that added this feature. The changes matched the commit message "- fixed various bugs on saving/opening XML scripting files" and did not appear to add the requested feature. I also did a cursory grep through commits with the word "snapshot" in them and didn't find this feature.

Would appreciate if someone could tell me how to use this feature.

**Comment by jvarley** [comment]
Interested in this as well...

**Comment by ptrckqnln** [comment]
As would I.

**Comment by cignoni** [comment]
To use this feature you have to try (at your own risk :) ) the prerelease builds; 
you can found them here:
- dmg for osx: https://github.com/cnr-isti-vclab/meshlab/releases 
- portable version for win https://ci.appveyor.com/project/cignoni/meshlab/build/artifacts

**Comment by rosenb0rg** [comment]
has anyone found a solution for this? I can't quite figure out how this works from the code.

**Comment by varun-tangoit** [comment]
Hi, can you please suggestion, how to use this feature. i don't know how to do this.

**Comment by jjpepper** [comment]
@cignoni has this made its way into the latest release? How do we use the feature with MeshLabServer?

**Comment by brunodutailly** [comment]
I got it:

1. run **GPU Filter Example** (in Raster layer)
2. setup your image to render. Note that alpha works fine in the color picker interface even if the filter dialog shows only RGB code
3. apply
4. go to **filter** menu -> **Show current filter script**
5. save the script
6. run your script in meshlabserver command line

BUT: I tried on a textured PLY and it renders without the texture.  In the code, the vertex and fragment shader are very basics and don't support texture.

Moreover, my PLY is Z up oriented and not centered, so I tried a rotation -90 on X axis with the filter rotate. Works fine in meshlab, the rendered image shows my mesh in the right orientation, but the rotation did not work in meshlabserver (matrix freezed or not and applied to all layers or not). Still no success on adding Freeze Matrix filter. Camera rotation filter seems to work but I lost my mesh, probably because it is not centered, or a camera rotation center issue...
