### ISSUE TITLE
GUI regression: Popups broken on Linux Xorg tiling window managers

### ISSUE THREAD

**Issue by nh2** [cnr-isti-vclab/meshlab#1209]
In Meshlab 2021.10 there is a regression that filter popups disappear if moved using Xorg's move-window functionality (it might also have been introduced or another relatively recent version, but I'm testing with 2021.10).

For example, I use the `i3` tiling window manager, and if the window is moved with the key combination for that (ModKey + drag, in my case that's CapsLock + drag), the popup disappears.

This makes it very difficult to work with filters where you apply a preview and then need to look at the mesh, moving the filter popup to the side to see what is happening.

Dragging the popup's title bar does not create the problem.

But a similar issue happens if I don't use ModKey+drag, but instead focus the main meshlab window. This also disposes the popup window.

Here's a video that shows the problem:

https://user-images.githubusercontent.com/399535/154069848-f84f7ddf-385b-415e-b420-1c8d18d07068.mp4

Any clue what change might have caused this?

**Comment by alemuntoni** [comment]
No, I really don't have any clue. The dialogs have been refactored since 2021.07 to support scroll areas, but the behavior  you described has always been random on different OS, windowing systems and even different packages (e.g. on my side, the behavior of the dialog "disappearing" changes if I use flatpak, appimage, or the my build)...
I just guess that using the QDockWidget class is not the best option for this use case...

**Comment by alemuntoni** [comment]
This issue should be fixed in the last commit!

**Comment by nh2** [comment]
Thank you, it did fix it for me!
