### ISSUE TITLE
Crash on "Delete all non visible Mesh Layers"

### ISSUE THREAD

**Issue by ErlerPhilipp** [cnr-isti-vclab/meshlab#1228]
MeshLab_64bit_fp v2022.02 on Win 10

How to reproduce:
1. Load several meshes (per drag&drop)
2. Delete at least one mesh layer either by right-click on the mesh layer + "Delete Current Mesh" or make one invisible + "Delete all non visible Mesh Layers"
3. Set at least one layer to invisible (click on eye button)
4. Right click on any mesh layer + "Delete all non visible Mesh Layers"
5. Freezes and crashes

This doesn't seem to depend on the meshes. I use small point clouds in PLY format. This bug was already present for me in earlier versions where it crashed on the first "Delete all non visible Mesh Layers", I think. Something changed but it's not fixed.

Btw. working with many (50+) layers is a pain. There seems to be quadratic complexity somewhere when adding layers, which leads to freezes of multiple seconds.

**Comment by alemuntoni** [comment]
Thanks for reporting. I'll look into this.

**Comment by alemuntoni** [comment]
The issue should be fixed in the last commit, if I reproduced it correctly.
You can try it by downloading the last [nightly](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version) (will be ready shortly). If you can check if it works fine, it would be appreciated :)
Thanks again for reporting!

**Comment by ErlerPhilipp** [comment]
That was really quick. I just tried it and it works now. Thanks a lot for all your work!
