### ISSUE TITLE
Menu command "Render -> Show Camera" does not show the view frustum

### ISSUE THREAD

**Issue by alessandro-gentilini** [cnr-isti-vclab/meshlab#131]
I would like to see my camera as a view frustum as I can see in this screenshot. http://www.meshlab.net/img/Feature/Raster.jpg

I have tried to follow the instructions here https://sourceforge.net/p/meshlab/discussion/499533/thread/cc40efe0/?limit=25 but with no luck: when I check "Render -> Show Camera" nothing happens while I was expecting to see the view frustum located at point labeled with 96.

My version is v2016.12.

I attached the `.mlp` and the `.ply` files, each one has extension `.txt` that must be removed.
[test.mlp.txt](https://github.com/cnr-isti-vclab/meshlab/files/920009/test.mlp.txt)
[test.ply.txt](https://github.com/cnr-isti-vclab/meshlab/files/920010/test.ply.txt)

**Comment by mcallieri** [comment]
This is because that is not a valid MLP file. 

A camera is valid only if associated to a raster layer, like in the following example.
Cameras do not exist "free" int he project space

`
<!DOCTYPE MeshLabDocument>
<MeshLabProject>
 <MeshGroup>
  <MLMesh filename="nano_100k.ply" label="nano_100k.ply">
   <MLMatrix44>
1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 
</MLMatrix44>
  </MLMesh>
 </MeshGroup>
 <RasterGroup>
  <MLRaster label="DSC_6554.JPG">
   <VCGCamera PixelSizeMm="0.0132169 0.0132169" CenterPx="1936 1296" ViewportPx="3872 2592" RotationMatrix="0.999983 0.0057209 -0.000838694 0 -0.00550346 0.986218 0.165359 0 0.00177314 -0.165352 0.986233 0 0 0 0 1 " FocalMm="85.645" TranslationVector="3.7863 206.162 -30.0264 1" CameraType="0" LensDistortion="0 0"/>
   <Plane semantic="1" fileName="DSC_6554.JPG"/>
  </MLRaster>
 </RasterGroup>
</MeshLabProject>
`

**Comment by alessandro-gentilini** [comment]
OK, thank you.

Now I am able to see the camera... I had to struggle a bit with `TranslationVector` because, as I found [here](http://vcg.isti.cnr.it/vcglib/shot.html):

> the translation matrix "tra" corresponds to -viewpoint

Is there any official doc for MeshLab? The "Help -> Online Documentation" just sends me at http://www.meshlab.net/ where I cannot find any doc...
