### ISSUE TITLE
libIFXCore / Exporting / Scheduling shared libraries are built/installed although unused

### ISSUE THREAD

**Issue by StefanBruens** [cnr-isti-vclab/meshlab#1353]
libio_u3d statically links to libIFXCore and no longer uses the standalone IDTFConverter.

The libraries should neither be built nor installed.

**Comment by alemuntoni** [comment]
Are you sure about this? 
libIFXCore, libIFXExporting and libIFXScheduling are built as modules. They are libraries that are loaded at runtime (this is how the idtf-u3d converter works -- [this one](https://github.com/ningfei/u3d). [My fork](https://github.com/alemuntoni/u3d) just reorganizes files and allows to convert easily without executing a binary).
If you just try to remove these library, the u3d exporter won't work.

**Comment by StefanBruens** [comment]
This was true for the 2022.02 release, which linked to u3d statically:
https://github.com/cnr-isti-vclab/meshlab/blob/58731df6d68e4edeb45d36e7c8828a9d46f8799a/src/meshlabplugins/io_u3d/CMakeLists.txt#L14

I think the changes for u3d are quite wrong - it is a vendored library, and with no proper upstream (or is the intention to become the official upstream?), statically linking u3d is the better option.

As far as I can see, the bundled (downloaded) `u3d` is build with `option(U3D_USE_SYSTEM_EXTERNAL_LIBS "Use system libraries for jpeg, png and z instead of bundled ones" OFF)`. This becomes an absolute nightmare if there are any differences between the libraries used in u3d and meshlab -either because meshlab uses sytem libraries, or when you forget to update always both in sync, or when the compile flags differ. `u3d` must always use the exact same `libpng` etc. as meshlab.

**Comment by StefanBruens** [comment]
Forgot to mention, meshlab does not link to libpng etc. itself, but Qt does, so you have to make sure Qt is build with the exact same versions as u3d.

**Comment by alemuntoni** [comment]
> This was true for the 2022.02 release, which linked to u3d statically:
> 
> https://github.com/cnr-isti-vclab/meshlab/blob/58731df6d68e4edeb45d36e7c8828a9d46f8799a/src/meshlabplugins/io_u3d/CMakeLists.txt#L14

Nope, it is true also right now, whether the converter (`external-IDTFConverter` before, now just `IDTF`) is built `STATIC` or `SHARED`.  libIFXCore / Exporting / Scheduling are loaded at runtime and must be built as modules on linux/macos, and as shared on windows. And they must be deployed in a specific directory w.r.t. the position of the plugin, in order to allow the plugin to find them when it needs to load them.

> I think the changes for u3d are quite wrong - it is a vendored library, and with no proper upstream (or is the intention to become the official upstream?), statically linking u3d is the better option.

u3d was adapted also in version 2022.02. I don't know if right now it could become the official upstream -- my changes are minor and are made to allow a proper integration in meshlab.
I just created another library IDTF that allows the conversion using a function. Before my change, I had to make a system call to execute a binary (that needed to load the IFX libraries at runtime). It was just impossible to make it work on all the platforms, considering that binaries and libraries must be placed in different paths depending on the used system.

> As far as I can see, the bundled (downloaded) `u3d` is build with `option(U3D_USE_SYSTEM_EXTERNAL_LIBS "Use system libraries for jpeg, png and z instead of bundled ones" OFF)`. This becomes an absolute nightmare if there are any differences between the libraries used in u3d and meshlab -either because meshlab uses sytem libraries, or when you forget to update always both in sync, or when the compile flags differ. `u3d` must always use the exact same `libpng` etc. as meshlab.

This should not be an issue, because if the option `U3D_USE_SYSTEM_EXTERNAL_LIBS` is OFF, then jpeg, png and z sources will be built along the `IFXCore` library:

https://github.com/alemuntoni/u3d/blob/8c2b04c5b987264ef69c5d48e96f17c4cc04b91b/cmake/IFXCore.cmake#L464

Nobody links png, jpeg and z, and nobody links `libIFXCore` because it is loaded at runtime by the u3d plugins.

In general, this u3d converter is a big mess. But it is also a feature that is highly requested in MeshLab, and the only open source code available is that one. I just adapted it as best as I could. But it was integrated in a much much worse way on previous versions of meshlab, and, more importantly, it just didn't work everywhere (on pymeshlab on linux and macos, for example). Now it works, and as far as I know it should not generate conflicts with other libraries. On my system I have a version of `libpng` different from the one bundled in u3d, but everything works fine.
