### ISSUE TITLE
Different behaviour between meshlab and pymeshlab 

### ISSUE THREAD

**Issue by mcarbotta** [cnr-isti-vclab/meshlab#1442]
I have a very weird issue using pymeshlab 2022.2 on ubuntu 22.04: the isotropic remeshing function behaves differently with the same options between the graphical user interface and pymeshlab. 

I'm trying to remesh a gyroid surface and using the default settings for the explicit isotropic remeshing.
The mesh generated in pymeshlab struggles with feature edges but if I run the same remesher with the exact same settings in the GUI it does not give any errors, here are the settings and meshes generated:

pymeshlab with the command:

ms.meshing_isotropic_explicit_remeshing(
 
iterations = 30
 
)

![image](https://github.com/cnr-isti-vclab/meshlab/assets/124825006/c751784c-203f-4e7e-a8d7-ccc70d113240)

meshlab(GUI):

![image](https://github.com/cnr-isti-vclab/meshlab/assets/124825006/3c0b3855-f28c-4fc4-b960-9a84d7c3bd3d)

Even if I use smaller crease angles the problem persists with pymeshlab, this is very confusing, perhaps something has to be defined differently in pymeshlab? Or is it just a bug?

**Comment by alemuntoni** [comment]
Unlike the default version of MeshLab, PyMeshLab is built using double precision floating point numbers, that is the default precision used in Python. This allows to avoid precision loss when importing and exporting meshes, and when applying filters to them.
Therefore, some filters can behave differently from the default MeshLab version, especially those that are sensible to precision loss. To replicate the PyMeshLab behavior in MeshLab, you can use the double precision, which is available for download with a version number having the suffix "d" (e.g. MeshLab2022.02d). 

Since you are not the first user that runs into this misunderstanding, I added a paragraph in the PyMeshLab docs that will appear with the next version.
