### ISSUE TITLE
A lot of linker problem with newest meshlab version.

### ISSUE THREAD

**Issue by sngkhiem** [cnr-isti-vclab/meshlab#1479]
I build meshlab solution in Visual Studio 2022 and get these linker error.
Qt version 5.15.2 with mingw81_64
Cmake version 3.29.0
This is log file when i build from VS.
[log.txt](https://github.com/cnr-isti-vclab/meshlab/files/14841271/log.txt).

**Comment by alemuntoni** [comment]
I never used Visual Studio 2022, but MeshLab is built with CMake and any IDE that supports cmake should be able to build MeshLab.
But... Are you trying to link Qt built with mingw with MeshLab built with msvc? It just cannot work.

Anyway, closing because this is not an issue related to the meshlab source code or build system, but related with your specific setup.
