### ISSUE TITLE
Parameterization + registered rasters stucks always

### ISSUE THREAD

**Issue by Askanderre** [cnr-isti-vclab/meshlab#150]
Hey Guys!

There is a problem which I really would like to have solved:

Usally when I'm preparing a 3D model with Photogrammetry I'm doing more then 300 Pictures from the Area which I want to have digitalized. Usually I'm using the vertex color information on the faces because of the Problem, but this coudn't ne the solution or? 

When I loaded the Project (.NVM or .OUT - File) and closed the model and imported the final surface-model, where I want to have the Texture from the registered rasters applied I'm starting the "Parameterization + texturing  from registered rasters" Filter. I'm setting the Texture size (neither 4096 nor 8192 worked) and the only additional klick is with the UV-Stretching which is adived in a Video Tutorial. Now the filter starts but soon after it looks like that everything is freezing. Meshlab is without respond, the RAM stops even without reaching the maximum (sometimes more sometimes less Gb) and the CPU stops at 13% (btw why it's using only one core?) I would give all my CPU to the filter if it would work! :)

I reduced a 360 picture project that I delete each second so that's "only" 180 rasters within a Meshlab project. But also thsi didn't work out. I always have to close the whole program because even waiting for 6h (without joke) doesn't work out. I'm not getting any Texture.

Is there a limit of registered rasters which can be used? How is that Filter connected to computer resources? And of course: How can I solve that problem and getting finaly a Phototexture from the already registered rasters? :)

My Computer:

Windows 7 Prof x64
AsRock 990fx Extreme9
AMD FX-8120 eight-core
NVIDIA Quadro K5000
32Gb Ram 

Thanks in advance!

Alex

**Comment by mcallieri** [comment]
The texturing filter has severe limits in terms of number of images. It has been developed for a small set of very well registered images (5-10-20) and NOT to directly process hundreds of images calibrated using SFM (so, not very accurately calibrated). 

These are two completely different problems, and require  a completely different working strategy. The current algorithm subdivide the mesh in chunks, each assigned to the best single image, and assemble a texture from cropped parts of the original images. If there are too many photos, the process becomes exponentially longer, and the result is terrible due to fragmentation. 

SFM tools have a different way to create texture. We simply cannot work with that much images. Moreover, SFM calubration is not pixel-precise, so a different blending and global alignment is needed to avoid ghosting and blurrying.

When we have to do similar stuff, we start from the photographic set and cherry-pick very few photos for the job.
