### ISSUE TITLE
Cannot associate .ply extension to Meshlab on Ubuntu 14.04

### ISSUE THREAD

**Issue by antochny** [cnr-isti-vclab/meshlab#170]
Because of snap installation of Meshlab, ply or other formats cannot be opened automatically by association extension type to Meshlab app...

Any idea to solve this minor issue ?

**Comment by thebucc** [comment]
The problem is still there after almost one year. Trying to associate an extension to meshlab by right-clicking "open with other application..." doesn't work because meshlab doesn't appear in the application list. The reason and a fix are explained here:

https://ubuntugenius.wordpress.com/2012/06/18/ubuntu-fix-add-program-to-list-of-applications-in-open-with-when-right-clicking-files-in-nautilus/

Essentially, for the application to appear in the "open with" application list, it is necessary to add "%f" to 'exec' line in the .desktop file:

Exec=meshlab     -->    Exec=meshlab %f

Fiddling with the snap files after installation is messy because they are owned by root and read only, it should really be done at the origin, in the snap package.

**Comment by alemuntoni** [comment]
This issue has been solved in the PR #710. You can try it in [this](https://github.com/cnr-isti-vclab/meshlab/suites/755830068/artifacts/7807989) snap package, and it will be available in the next version (2020.07).
