### ISSUE TITLE
What is the preferred file format for triangle mesh + per-face colors?

### ISSUE THREAD

**Issue by alecjacobson** [cnr-isti-vclab/meshlab#182]
(apologies if this is a better question for stack overflow)

MeshLab can write and read a bunch of file formats for meshes with colors. Is there any knowledge about which is the most common / supported?

It seems the choices are:

- .ply 
- binary .stl (multiple conventions)
- .3ds
- .off (8bit color appended to face indices, will this mess up other loaders?)
- .obj (expands each color to a material, inefficient?)

Can .wrl (VRML) support per face colors?

I know that .stl is well supported for 3D printing. Do most .stl readers use the materialize color convention at this point?

**Comment by mcallieri** [comment]
PLY is the format we use, and for this reason is the one where we can save everything we can produce inside MeshLab.

for per-face colors I would say OBJ.

As far as I know, STL color encoding is not very common.

VRML and COLLADA  should work too, but there always seems to be issues with importers/exporters in the various software tools
