### ISSUE TITLE
Get info face picking / pick points don't work on Mac

### ISSUE THREAD

**Issue by isaactian** [cnr-isti-vclab/meshlab#197]
These features seem to work fine on Windows Meshlab but don't function at all on Mac. This was the case in the previous version as well.

**Comment by elaughli** [comment]
I have mixed success with this on my Macbook. I can't quite pinpoint it, but it seems like it only does face picking fine but can't toggle to vertex picking. So if I'm looking at a pointcloud with no faces, I can't select anything, otherwise with a surfaced mesh i have to select faces and get my point info from that.

**Comment by charmland** [comment]
yeah, on macOS High Sierra 10.31.1, [Get Info] tool can only pick faces but cannot pick vertex

**Comment by mcallieri** [comment]
unfortunately, we have set the "toggle" command, that switches from face picking to vertex pickign to SPACEBAR, which is used by MacOS as a system key... It was working until a couple OS version ago :( 
We have corrected it, using a different key, but we still do not have a release, sorry.

**Comment by MandyMo** [comment]
On mac, the bug that [get info] tool can only pick faces still exists.
