### ISSUE TITLE
[Feature Request] Storing multiple datavalues

### ISSUE THREAD

**Issue by Marriaga** [cnr-isti-vclab/meshlab#231]
I would like to **compute and export** 2 different quantities in a mesh (e.g. SDF and Mean Curvature).

I was wondering if it would be possible to implement (if it is not implemented already) a "filter" called "Create User Field From Quality" where the dialog box would ask for a string to serve as label for the new "_user field_" and the function would simply copy the _quality_ array to a new location in memory.

Then, to export this data, there could be an extra checkmark called "User Fields" where all the user fields that were created by this function would also be exported. In the ply format this is quite straight forward.

**Comment by mcallieri** [comment]
Hi. 
It is possible to create a per-vertex field, and assign a value to it, with the filters. However, it is not currently possible to SAVE this value.
Yes, it is silly, I know. Especially because we do this on other internal tools.
It is on the to-do list... I cannot give you a time estimate, however.

**Comment by Marriaga** [comment]
Thanks for letting me know. May I ask which filter can be used to create a per-vertex field? I can't seem to find it.

I would also be happy to help implement this.

**Comment by mcallieri** [comment]
"Define New Per Vertex Attribute", it is under "Mesh Layers"
