### ISSUE TITLE
Crash upon start

### ISSUE THREAD

**Issue by jfraley0415** [cnr-isti-vclab/meshlab#246]
I recently downloaded MeshLab 2016 but cannot access. The software crashes as soon as I try to open it. Do you have any suggestions for me?

**Comment by chipweinberger** [comment]
I've had the same problem for a long long time. Tried all the suggestions. But no avail. Hopefully they release new binaries soon...

**Comment by richgain** [comment]
I'm trying to run MeshLab2016 on my Surface Pro 3 but I'm having this same issue.
Two small windows pop open very briefly and then disappear again.

Are any log files generated that would help debug this?

**Comment by gutierrezps** [comment]
Same here. Windows 7 SP1 x64.

**Comment by mcallieri** [comment]
MeshLab crashing at startup is generally a videocard-related issue.
- if you are on a notebook with integrapted AND accelerated videocard, try using the accelerated one
- update drivers.

on some machines, with only interated videocards, MeshLab is unable to start because the videocard does not support some shader features.
Surface Pro 3 is not even a PC...a nd has an integrated videocard from 2014. I would not recommend to use it for 3D processing.
Windows 7 has been discontinued since 2015... and service pack 1 is from 2010...
