### ISSUE TITLE
Can't import .pts file: invalid framebuffer operation

### ISSUE THREAD

**Issue by marcodileo** [cnr-isti-vclab/meshlab#248]
I can't manage to import a point cloud file, .pts file.
Any idea?

**Comment by mcallieri** [comment]
the invalid framebuffer operation message in MacOS is generally caused by a bug in QT, and generally has no effect on the tool.
Beware that .pts is a very specific format, but some tools just call pts any "ascii point cloud".
If your file is indeed just an ascii list of points, one point per line, rename it .txt and use the generic loader. You will have to specify what is the actual content.
