### ISSUE TITLE
Filterscript filters seem to not serialize

### ISSUE THREAD

**Issue by rajarshiroy** [cnr-isti-vclab/meshlab#254]
I am running Meshlab 2016.12 in windows 10 64bit.
I opened and applied filter script with multiple filters:
1) Filters>Show current filter script
2) Open Script
3) Apply Script

The various filters in the script seem to be executing in parallel. A filter that consumes the mesh (Small Component Selection) from a previous filter step (Screened Poisson) is executing before the Screened Poisson step is over. Is this expected?

**Comment by mcallieri** [comment]
mmm... two things:
1) script management has a lots of problems, in the 2016 version. We have fixed varipus bugs, and we are testing it now
2) I believe the problem is the CURRENT layer. The script only records the list of filters used, but does not include the "change of layer". The Pioisson merging create a new layer, but the CURRENT layer is still the original one, so, even if the "remove small components" is executed after the Poisson, it is executed on the first, original layer.

**Comment by mcallieri** [comment]
If you need to apply the second filter to a specific layer, to include it in the script, chenge the current layer using the specific filter (under the mesh layer Group), OR, just delete the current mesh, that is the original one, this, making the poisson merging the new current.
