### ISSUE TITLE
absolute value and percent of value in meshlab server

### ISSUE THREAD

**Issue by tjgallaher** [cnr-isti-vclab/meshlab#262]
There are several filters for which you can specify an absolute value or a percent in meshlab. For example the VCG filter, Subdivision surface and Remove Isolated Pieces. I would like to use a constant percentage in meshlab server for multiple files but the script only seems to take a value and I can not figure out how to instead calculate the percent. Does anyone have an example of script that I can use that will calculate the percent of the value. 

For example: 
filter name="Surface Reconstruction: VCG"
Param tooltip="VoxelSide" name="voxSize" max="22.7628" type="RichAbsPerc" description="Voxel Side" value="0.22763" min="0"/

The 0.22763 and 22.7628 values makes sense for one of my files but they would not make sense for the remaining files. I do not want to have to manually change this each time. Thank you so much for your help.

**Comment by mcallieri** [comment]
If I am not mistaken, if you just fill the PERCENTAGE, and leave the absolute value to 0, the filter will auto-compute the value given the percentage.

**Comment by 3DLIRIOUS** [comment]
You can accomplish this, but it is a bit cumbersome.

1. First, you need to determine how to convert from a percentage to the absolute value that meshlabserver requires. For many filters (most? all?) the absolute value is computed by multiplying the percentage by the mesh bounding box diagonal.
2. Run meshlabserver to measure the parameters you need, such as using filter "Compute Geometric Measures" to measure the diagonal.
3. Compute the absolute value using the parameter(s) found in the previous step
4. Run meshlabserver a second time with your desired filter, using the absolute value found in the previous step as the relevant filter parameter.

Step 2 seems inefficient, since MeshLab appears to store many parameters internally (including the diagonal), however there doesn't seem to be any way to access these internal values from scripts. Issue #200 is a feature request to allow meshlabsever to reference these internal values, which would simplify and speed up this process considerably.

Lastly, as a shameless plug, if you do a lot of meshlabserver scripting you may want to check out my python library [MLX](https://github.com/3DLIRIOUS/MeshLabXML). :)
