### ISSUE TITLE
Meshlab will not start on Windows 10

### ISSUE THREAD

**Issue by RoelHeer** [cnr-isti-vclab/meshlab#275]
After installing Meshlab on my Windows 10 Pro laptop it will not start. There are only 2 windows opening and closing very fast, so I cannot see a warning message. I thought it had to do with Microsoft Visual C++ 2015 Redistributable (x64), as this was not installed (the 2017 version was already installed on my PC). After installing Microsoft Visual C++ 2015 Redistributable (x64) the problem persisted. I will now restart my PC and see what will happen.
Does anybody know how to handle this?

**Comment by mcallieri** [comment]
There might be problems with the videocard. Mehslab, since the 2016 update heavily rely on GPU acceleration.
- notebooks, most of times, have 2 videocards, one integrated and one accelerated, be sure to use the accelerated one
- update graphics drivers

If you only have an integrated videocard not fully supporting advanced GPU features, there are some problematic combinations of HW/drivers on which MeshLab is unable to run.

**Comment by RoelHeer** [comment]
Yes, I did notice so. Fortunately I have 2 videocards. 1 is the integrated Intel HD Graphics 3000 card and the other a NVIDIA GeForce GT 525M. Meshlab works well when connected to the NVIDIA card.

Thanks for your support!
