### ISSUE TITLE
Error Reading OFF File

### ISSUE THREAD

**Issue by SteveMiller** [cnr-isti-vclab/meshlab#292]
I have created an OFF-formatted file (see attached) that I think follows the prescribed format. When I try to open it in MeshLab 2016.12 I get an “invalid file error”.

I am using the mesh import icon and the program starts, but then gives the message and crashes.

I am certain that the file format is wrong somehow, but I have re-checked it several times against available web sites  that describe the format.  The file is a sample of 1153 LiDAR points that have been created into a TIN.  The 1153 nodes have color info (RGBA) as well as the XYZ of the points.  The 2288 triangles follow the points with three indexes that are linked to the nodes.  I have indicated no edges in this data by specifying “0” as the number of edges.

Hopefully this is a stupid error on my part.

Thank you for taking time to address this issue.

**Comment by SteveMiller** [comment]
Here is the attachment

[OutOFF - Copy.txt](https://github.com/cnr-isti-vclab/meshlab/files/1786928/OutOFF.-.Copy.txt)

**Comment by mcallieri** [comment]
Hi there, 
   as explained here:
http://www.geomview.org/docs/html/OFF.html
if color is present, the first row of headr should be COFF and not OFF. Basically, this row tells the system which data is present, beside the XYZ coordinates.
You may change the file in a text editor and it works.

HOWEVER, when you load it, you will see a wobbly geomety.
This is because the XYZ coordinates in the file are HUGE numbers. very far from origin, and there are problems with number precision, when rendering. The solution is to keep your dataset closer to origin.
