### ISSUE TITLE
UniformMeshResampling fails for pointed objects.

### ISSUE THREAD

**Issue by SteveBaker** [cnr-isti-vclab/meshlab#303]
This is a uniform mesh resampling of an object with a sharp angle at one end...the resulting mess has holes in it and lots of debris.

![meshlabuniformmeshresamplingscrewup](https://user-images.githubusercontent.com/651871/38395220-7ed53282-38f7-11e8-8617-e08a5a541738.png)

Dozens of other pointy objects show the same problem so it's not a "one-off" due to some weirdness of this particular mesh.

**Comment by mcallieri** [comment]
Hi. you are using a very old version of MeshLab.

the issue is related to volumetric resampling. Sharp corners have always been the weak point of marching cube algorithms. Try with a lower "precision" parameter; this will make the volume cells smaller, resulting in crisper edges. In any case, small unconnected parts can always appear, but may be easily removed.
