### ISSUE TITLE
2016.12 is the newest version ?

### ISSUE THREAD

**Issue by CandyFather** [cnr-isti-vclab/meshlab#328]
I installed 2018.04 in Mac OSX,when I click Help-Check for Updates I will get the message
"You are using an old version
 MeshLab 2016.12 has been released the 24th of December 2016.
Please,upgrade to the new version!
Download
OK"
![image](https://user-images.githubusercontent.com/1396270/41345421-251f967c-6f36-11e8-953a-1ebe792d9421.png)

**Comment by mcallieri** [comment]
you are running the correct version (latest beta), is the check that is buggy :(
sorry

**Comment by oleg-alexandrov** [comment]
The check was apparently fixed on the server side (I don't the pop up anymore). Now, if Meshlab calls home the way it usually does, like this:

http://vcg.isti.cnr.it/~cignoni/meshlab_latest.php?code={333beac3-b3a3-4e9f-bf89-f3333333dc33}&totkv=182180&ver=2018.1&os=Lin

to say that your version is from 2018, it will respond saying ok, meaning that it is good enough, rather than you need to upgrade.

Also, in the code, logic was added so that the user be allowed to turn off this pop-up from coming up in the future. (https://github.com/cnr-isti-vclab/meshlab/pull/552)  

Hence this issue can be closed.
