### ISSUE TITLE
Issue with .u3d export

### ISSUE THREAD

**Issue by cclaudio78** [cnr-isti-vclab/meshlab#33]
I import a .obj file created with blender. When I try to export it to a .u3d file with MeshLab, I get the following message:

'Missing converter executable 'C:/Program Files/VCG/MeshLab/plugins/IDTFConverter.exe'

Thanks for any help

**Comment by granzuglia** [comment]
I confirm the issue. It will be fixed in the next MeshLab release. Anyway there is an easy workaround if you need it immediately.
- Go to https://github.com/cnr-isti-vclab/meshlab/
- press on the green button "clone or download" then on the button "download zip"
- open the zip and go to the folder  meshlab-master\src\distrib\plugins
- there copy the folders U3D_OSX and U3D_W32
- open the folder where you installed MeshLab (if you are on windows usually it should be C:\Program Files\VCG\MeshLab)
- paste the two folders in C:\Program Files\VCG\MeshLab\plugins
- run again MeshLab and you should not have the problem again

Thanks for the acknowledgement and sorry for the inconvenience! We will fix it as soon as possible!

**Comment by marabout2015** [comment]
Was this ever fixed? I downloaded MeshLab for Windows 64, and I have this error on export. My version was downloaded today, 2019-05-01, and the About reports I have MeshLab_64bit_fp v2016.12 (built on Dec 23 2016)

**Comment by LAOMUSIC** [comment]
NO, it is NOT fixed! I just did two times and all I´ve got is still the "tex" file but no u3d !

**Comment by cliftontaylor1** [comment]
Trying to go from .stl to .u3d, still, giving me the error. Anyone have a fix?

**Comment by alemuntoni** [comment]
Could you please try the new meshlab version that you can find in the [release](https://github.com/cnr-isti-vclab/meshlab/releases) tab?

**Comment by dsvcom** [comment]
I tried with MeshLab 2020.02 with the same result. Export Mesh As U3D only generates a small file with the .tex extension instead of a .u3d file.

Anyone find any workarounds?

**Comment by alexmyczko** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=629171

this issue should be opened, as the ./distrib/plugins/U3D_*/bin/IDTFConverter only comes as a binary. where's the source to it?

**Comment by alemuntoni** [comment]
@alexmyczko see #495

**Comment by worm6666** [comment]
https://github.com/cnr-isti-vclab/meshlab/issues/495#issuecomment-609449356
