### ISSUE TITLE
Failed Decorate mode Show Quality Histogram

### ISSUE THREAD

**Issue by jeyasri-s2** [cnr-isti-vclab/meshlab#337]
I have compared two meshes in meshlab V2016.12.
after colorize by vertex quality, Meshlab is not able to render 'Quality histogram'
I tried uninstalling the software and reinstalled back.

**Comment by mcallieri** [comment]
it works for me.
Are you sure you you have selected the correct layer (the one with vertex quality)?

**Comment by fishdda** [comment]
I have met the same issue as I try to calculate the curvatures of the PTV surface mesh
![image](https://user-images.githubusercontent.com/23411165/101302917-d0c88d00-3877-11eb-878a-08c438ebab83.png)

**Comment by alemuntoni** [comment]
Could you please share a reproducible example? (e.g. share the file you are using, and the list of operations that cause the issue)

**Comment by fishdda** [comment]
https://drive.google.com/file/d/1hwysIFxEMkLXtgEpD-tFY8JgejzKqQZo/view?usp=sharing

**Comment by fishdda** [comment]
I tested it on windows 10 and MeshLab version is 2020.12

**Comment by alemuntoni** [comment]
Assuming that you just open the mesh and start the decorator (cause you didn't answer to my question on listing the operations that cause the issue), the log tells perfectly why the quality histrogram is not shown:
```
Error in Decorate mode Show Quality Histogram: 
CANNOT START DECORATOR: the layer contains neither vertex nor face quality
```
What is the issue here????

**Comment by jabrucohee** [comment]
Hey there, this might be a good point to reopen this thread. I hae issuer rendering a quality histogram. When I open the 
"brain.ply" from the example meshes and then apply the filter "discrete curvature" with the option "mean curvature", I do get the colouring, but when I press show quality histogramm I get:

`Failed Decorate mode Show Quality Histogram`

In fact since yesterday or so I cannot render any Quality Histogramms. I tried reinstalling meshlab but no luck!

Any ideas? I am running meshlab on Ubuntu 22.04.

Any idea what this could be caused by?
