### ISSUE TITLE
cannot get meshlab 1.3.3 on ubuntu arm

### ISSUE THREAD

**Issue by nosarious** [cnr-isti-vclab/meshlab#342]
I am hoping to install meshlab on a NVidia Jetson TX2.

When I go through the usual method of installing using ppa, I only get 1.3.2+dfsg1-2build4 When I check to see if there are updates, I am told there is a new version which I should download.

I enjoy my current version, but I would like to explore the new poisson surface thingie ... "screened poisson surface reconstruction filter" as it sounds sexy and useful.

The NVidia has an arm processor. I am running Ubuntu 16.04.5 LTS (driver-specific for NVidia developer computer)

**Comment by mcallieri** [comment]
A lot has changed since version 1.3.2
Unfortunately, the SNAP package seems to be broken, now :( 
As MeshLab now uses a lot more the GPU, you may have issues for some filters, I have no idea how the Jetson driver works. The same for compiling some filters, we never used it on an ARM.

in any case, instructions on building MeshLab for Ubuntu have been updated here:
https://github.com/cnr-isti-vclab/meshlab/blob/master/src/README.md

**Comment by alemuntoni** [comment]
I'll close this issue since it refers to an old and not anymore supported ubuntu version.
Feel free to open another issue if the problem persists in newer versions.

**Comment by johnnynunez** [comment]
https://forums.developer.nvidia.com/t/meshlab-2023-12/305249
