### ISSUE TITLE
Problem in use model exported by Agisoft Photoscan

### ISSUE THREAD

**Issue by SimoneG82** [cnr-isti-vclab/meshlab#369]
Hi, when I work with obj exported from Photoscan and prepared with Meshlab 2016 in ply format, the nexus programm report to me an error:1 and don't process the file.
A follow an internet guide on 3Dhop http://3dhop.net/documentation/3DHOP_Models_Preparation.pdf but no result. There are an options or filters that I must use/apply to obtain a correct ply model for nexus?

**Comment by potenziani** [comment]
Hi, it's very hard trying to identify the error from these few lines... 
You should try to run nxsbuild.exe from the command line (usually in this way you get more details on the error). Anyway, most of the time this kind of error is related to missing textures (or to wrong textures paths), so a preliminary action would be to check if everything is ok from this side (if your model has textures). 
However, if any of these tips help you in identifying the issue, consider to send us the .ply file. 

Ps: probably this is an issue that fits better to the Nexus GitHub repository rather than this.
