### ISSUE TITLE
MeshLab quits unexpectedly while importing .xyz mesh

### ISSUE THREAD

**Issue by RobertoMinelli** [cnr-isti-vclab/meshlab#413]
As per screencast attached, MeshLab quits unexpectedly while trying to import the .xyz mesh file attached. From time to time, the import succeeds, but the Surface Reconstruction fails, i.e., again MeshLab quits unexpectedly. What could I do?

**Specs:**
MeshLab v2016.12
macOS 10.14.2 (18C54)
MacBook Pro (15-inch, 2018)
2.9 GHz Intel Core i9
32 GB 2400 MHz DDR4
Radeon Pro 560X 4096 MB

**Attachments:**
Screencast to show the problem 
.xyz file used in the video
Error log from 

[MeshLab-Failure.zip](https://github.com/cnr-isti-vclab/meshlab/files/2803724/MeshLab-Failure.zip)

**Comment by mcallieri** [comment]
There is nothing wrong in the file, as far as I can see, I have no problems in opening it on multiple machines using 2016.12 and the new beta. 
Surface reconstruction fails because you have no normals. Almost all surfacing algorithms require normals. Try ball pivoting, it works, more or less.
And, anyway, any surface reconstruction method will struggle with this… two surfaces very close one another, same point distribution. I am not sure a geenric algorithm is good for this procedurally made cases. I'd try triangulating each surface independently, and then flatteining the two.
