### ISSUE TITLE
Max Texture Size?

### ISSUE THREAD

**Issue by NPatch** [cnr-isti-vclab/meshlab#440]
Trying to open a PLY file that uses a 32k x 32k jpg texture. An error is thrown that there's a problem with loading the texture, twice. Is this a texture size limitation? If so, what is the max texture size?

**Comment by mcallieri** [comment]
the maximum size of the texture follows the limits of the videocard driver.
MeshLab loads the texture in videocard memory as a single piece; if the texture is larger thant he max available size, it is scaled down. All realtime software do this (but sometimes they do it without telling you :) )
32K textures may be used in offline rendering tools (maya, blender, 3DS) because they are stored in RAM, and accessed through CPU. In realtime appplications, having a single 32K texture is not a good choice, as it will eat up a lot of VRAM without any possible optimization.

**Comment by NPatch** [comment]
Thx, I forgot about this. Actually I found out that most drivers will cap at 16kx16k textures. So the result is usually multiple textures(e.g. OBJ with multi material setup, 1 material per texture). The texture was generated from different software so I had no way to view it. Btw Meshlab freezes when I give it such an OBJ. I think I haven't managed to open such a multi material obj even once.
