### ISSUE TITLE
"There are gl errors: invalid operation"

### ISSUE THREAD

**Issue by nyotis** [cnr-isti-vclab/meshlab#45]
Where I can get the log for this cryptic family of bugs - all filtering operations end-up like this? I am on mac OS X 10.12.2 with a discrete nvidia card (NVIDIA GeForce GT 650M 1024 MB)? Which version of GL shaders (> 3.1 I believe) is MeshLab currently supporting? 

NY

**Comment by granzuglia** [comment]
The issue is well known. They are all (or, at least, the one we know...) derived from the Qt framework implementation on Mac OSX. Unfortunately, even if we tried really hard, it seems to be impossible to remove them.

**Comment by nyotis** [comment]
i am impressed _at the ease_ that you just close bugs...

Maybe if you show me the log I might be able to help.. What's the use of "updated" Meshlab if it cannot handle basic GL operations? Which version of Qt are you using? Are you using Qt's 5.1 interpretations of OpenGL or are you using ARB_extensions which are infamous for not working well with Qt? More info please

**Comment by cignoni** [comment]
Sorry for the lack of explanations. 
It is an issue that is not really critical (they are warning) and quite hard and complex to be solved.
So it is not on the top of the priorities. 

To be more precise it is due to our, deprecated use of QGLWidget instead of QOpenGLWidget. 
As was discussed here:
http://stackoverflow.com/questions/33545006/qt5-attempt-to-set-a-screen-on-a-child-window-many-runtime-warning-messages
this is probably a bug in Qt that will not be fixed...

**Comment by nyotis** [comment]
fair enough @cignoni
