### ISSUE TITLE
qmake -spec error on Ubuntu

### ISSUE THREAD

**Issue by misan** [cnr-isti-vclab/meshlab#467]
The suggested vars for qmake
```
QMAKE_FLAGS=('-spec' 'linux-g++' 'CONFIG+=release' 'CONFIG+=qml_release' 'CONFIG+=c++11' 'QMAKE_CXXFLAGS+=-fPIC' 'QMAKE_CXXFLAGS+=-std=c++11' 'QMAKE_CXXFLAGS+=-fpermissive' 'INCLUDEPATH+=/usr/include/eigen3' "LIBS+=-L`pwd`/lib/linux-g++")
MAKE_FLAGS=('-j11')
```

give an error when running on Ubuntu (tested on 16.04 and 18.04) 
```
$ qmake external.pro $QMAKE_FLAGS
***Option -spec requires a parameter
```
I fixed it by replacing '-spec' 'linux-g++' by '-spec linux-g++'

**Comment by bimalkharel** [comment]
Do you publish the built binaries for Ubuntu here?

**Comment by bimalkharel** [comment]
I set up a vm with the build tools and qt but ran into many errors on 18.04

**Comment by misan** [comment]
I describe here
http://fightpc.blogspot.com/2019/07/the-art-of-compiling-meshlab-and.html
how I managed to get a working binary on 18.04.

**Comment by bimalkharel** [comment]
Thanks! So in the end you could not build the latest release it sounds like. You had to revert to the 2016 code base? @mcallieri @potenziani any chance you can build a linux binary using linux as the build target in your existing setup? I am sure there would be a lot of grateful people :)

**Comment by misan** [comment]
I was able to build the last versión but it was crashing on functions that
worked ok on the 2016.12 version.

**Comment by hamoid** [comment]
The error happens because it ignores everything after the space, so it runs only

    QMAKE_FLAGS=('-spec'

Doing tests, I managed to get to the next step by typing (replace MYUSERNAME and that path. I did ```which linux-g++``` to find it)

    qmake external.pro -spec linux-g++ "CONFIG+=release CONFIG+=qml_release CONFIG+=c++11 QMAKE_CXXFLAGS+=-fPIC QMAKE_CXXFLAGS+=-std=c++11 QMAKE_CXXFLAGS+=-fpermissive INCLUDEPATH+=/usr/include/eigen3 LIBS+=-L/home/MYUSERNAME/Qt/5.12.2/gcc_64/mkspecs/linux-g++"

Then I'm stuck at the next step with

    Project ERROR: Unknown module(s) in QT: xmlpatterns script

even if I installed 

    sudo apt install libqt5script5
    sudo apt install libqt5script5

The reason I wanted to try the latest version is because filling holes in the mesh crashes for me.

**Comment by asnt** [comment]
> ```
> $ qmake external.pro $QMAKE_FLAGS
> ***Option -spec requires a parameter
> 
For info, with bash,
```
$ qmake external.pro ${QMAKE_FLAGS[@]}
$
```
The array must be expanded explicitly otherwise the first element is returned (as @hamoid mentioned).
https://www.gnu.org/software/bash/manual/bash.html#Arrays

**Comment by captnjohnny1618** [comment]
The following works for me on Ubuntu 18.04.  I'm writing up the full instructions so they're all in one spot.

I assume most of us are using BASH, however the instructions given in the README.md seem to be using a different shell (i.e. why the QMAKE_FLAGS aren't being properly configured).

Install Qt stuff:  
`$ sudo apt-get install qt5-default libqt5xmlpatterns5-dev qtscript5-dev`

Clone VCGLib and **SWITCH TO DEV BRANCH** (note, this is why @hamoid was getting the ReadHeader error).  Let's assume you're cloning into the directory `$SRC_DIR` which is set to something like `/home/USERNAME/Code/`.  I'd recommed using absolute paths since they seem to be more reliable and we're going to use SRC_DIR below in the qmake commands.
```
$ cd $SRC_DIR
$ git clone git@github.com:cnr-isti-vclab/vcglib.git
$ cd vcglib && git checkout devel && cd ../
```

Clone Meshlab into the same parent directory as VCGLib (i.e. if you run `ls` you should see "vcglib meshlab" in the same directory.  See [meshlab/src/README.md](https://github.com/cnr-isti-vclab/meshlab/blob/master/src/README.md) for more info if this is unclear):
`$ git clone git@github.com:cnr-isti-vclab/meshlab.git`

Now, we want to _mostly_ follow the instructions in the readme, however there's some stuff that doesn't work.  Namely when setting the QMAKE_FLAGS, I've found it easier to just pass them manually.  Note that they are slightly different for each qmake command (the -L library path changes depending on which directory you're currently building for).

First build `external` and `common`:
```
cd $SRC_DIR/meshlab
cd src/external
qmake external.pro -spec linux-g++ "CONFIG+=release CONFIG+=qml_release CONFIG+=c++11 QMAKE_CXXFLAGS+=-fPIC QMAKE_CXXFLAGS+=-std=c++11 QMAKE_CXXFLAGS+=-fpermissive INCLUDEPATH+=/usr/include/eigen3 LIBS+=-L$SRC_DIR/meshlab/src/external/lib/linux-g++" && make $MAKE_FLAGS
cd ../common
qmake common.pro -spec linux-g++ "CONFIG+=release CONFIG+=qml_release CONFIG+=c++11 QMAKE_CXXFLAGS+=-fPIC QMAKE_CXXFLAGS+=-std=c++11 QMAKE_CXXFLAGS+=-fpermissive INCLUDEPATH+=/usr/include/eigen3 LIBS+=-L$SRC_DIR/meshlab/src/common/lib/linux-g++" && make $MAKE_FLAGS
```

Now `meshlab_mini.pro` should build just fine:
```
cd ..
qmake meshlab_mini.pro -spec linux-g++ "CONFIG+=release CONFIG+=qml_release CONFIG+=c++11 QMAKE_CXXFLAGS+=-fPIC QMAKE_CXXFLAGS+=-std=c++11 QMAKE_CXXFLAGS+=-fpermissive INCLUDEPATH+=/usr/include/eigen3 LIBS+=-L$SRC_DIR/meshlab/src/lib/linux-g++" && make $MAKE_FLAGS
```

However if you try and build `meshlab_full.pro` you'll run into an error related to `lib3ds.a` not being found.  Assuming everything has worked up to this point though, you've already build it, qmake/make is just looking for it in the wrong directory.  The simplest workaround I've found is just run the following 

`cp external/lib/linux/* external/lib/linux-g++/`

Now running 
```
qmake meshlab_full.pro -spec linux-g++ "CONFIG+=release CONFIG+=qml_release CONFIG+=c++11 QMAKE_CXXFLAGS+=-fPIC QMAKE_CXXFLAGS+=-std=c++11 QMAKE_CXXFLAGS+=-fpermissive INCLUDEPATH+=/usr/include/eigen3 LIBS+=-L$SRC_DIR/meshlab/src/lib/linux-g++" && make $MAKE_FLAGS
```
should successfully complete and you should get all of the useful plugins.

I also ran into the same `lib3ds.a` error on 16.04 when I built meshlab for my work machine.  I think either the build chain needs to be drastically simplified or a script should be written for Ubuntu since it's probably the most widely used linux distro out there.  There's also some lingering configuration errors somewhere in the qmake setup scripts that need to be resolved.  Meshlab is great software but building from source shouldn't generally require this much sleuthing (and the Ubuntu binaries available in apt-get are woefully out of date)... :)

**Comment by alemuntoni** [comment]
I'll close this issue since it should be fixed with the last PR.
Feel free to open another issue if the problem persists.
