### ISSUE TITLE
Can't open a txt or e57 laser scanned point cloud file

### ISSUE THREAD

**Issue by nautarcher** [cnr-isti-vclab/meshlab#481]
Meshlab just can't open any kind of file I give it. Just keeps cycling. Why?

**Comment by jmespadero** [comment]
Please, remember to provide a minimal reproducible example of your data when reporting an issue. People will be better able to provide help if you provide the data that they can use to reproduce the problem.

**Comment by mcallieri** [comment]
We don't even have a e57 importer. It does not appear in the supported format list.
For txt, the problem is that txt and asc are format where each software saves whatever they want. It's a mess to make a universal importer able to deal with all the possible variations.
When importing a txt, meshlab ask you details about what is inside the file. If the files contains other things beside what is shown int he dialog, it may get stuck in importing it.
basically, txt importer is made to import ascii files with a vertex for each line, each line containing the coordinates and maybe some extra info (color, normal, reflectance).
reasons for it to get stuck:
- other fields we cannot parse
- comments and other data in the file
- multiple clouds in the same file, separated by blanks/text blocks/other stuff
- incoherence in lines (different lines have a different number of fields, differnt separators are used)

**Comment by brawer** [comment]
Feature request to support E57: https://github.com/cnr-isti-vclab/meshlab/issues/582
