### ISSUE TITLE
"Select Self Intersecting Faces" returns lots of false positives

### ISSUE THREAD

**Issue by matthieu-nesme** [cnr-isti-vclab/meshlab#50]
Hi,
(and thanks for this great software!)

the selection tool that computes intersections between triangles gives a lot of false positives (often triangles sharing a vertex, but sometimes very close but not touching triangles). Is it due to a hard-coded threshold?

I've got no idea if it also gives false negatives.

**Comment by unrealwill** [comment]
Hello,

I encountered the same problem with meshlab v1.3.2 (old version but couldn't update as snap installer is bugging on my machine) when rendering some quad fields. 

I simplified it to the following binary stl file which only has 2 non intersecting triangles with 6 vertices, but meshlab is selecting those faces as self intesecting.

[bugmeshlabSimplified.stl.zip](https://github.com/cnr-isti-vclab/meshlab/files/4112926/bugmeshlabSimplified.stl.zip)

The bug occur when rendering quad field with two triangles for a quad, there are two possibilities for 2 triangles of a quad (shared side along one diagonal or the other). The bug occurs when we change the diagonal we pick. The mesh can't be rendered as a triangle strip, but it isn't self intersecting.

**Comment by alemuntoni** [comment]
I checked this issue again, and I can confirm that false positives depend on numerical errors, and there is not much I can do.
The issue could be easily avoided by using the version of meshlab built with double precision (e.g. 2021.05**d**).

**Comment by pzpzpzp2** [comment]
I'm using meshlab 2022 and the problem is still here. Here's the obj file it can be repro'd on. Worse is it doesn't appear consistent. The farthest 2 triangles are selected as self intersecting, while pairs of triangles that are closer, and not in each other's 1-ring, are not marked as self intersecting. I don't think that makes sense if the detection is based on a threshold. That said, the threshold seems quite large - in this case it appears larger than 0.001

<img width="885" alt="Screenshot 2023-10-29 at 3 59 50 AM" src="https://github.com/cnr-isti-vclab/meshlab/assets/132926503/da089f34-4df8-4afa-bcd5-d9db005ef6b5">

####
#
# OBJ File Generated by Meshlab
#
####
# Object selfinter3.obj
#
# Vertices: 7
# Faces: 5
#
####
v 0.209761 -0.170992 -0.365366
v 0.209761 -0.168521 -0.365366
v 0.209761 -0.166050 -0.365366
v 0.209761 -0.163580 -0.365366
v 0.215208 -0.164724 -0.365436
v 0.215208 -0.162253 -0.365436
v 0.215208 -0.159782 -0.365436
# 7 vertices, 0 vertices normals

f 1 2 5
f 2 6 5
f 2 3 6
f 3 7 6
f 3 4 7
# 5 faces, 0 coords texture

# End of File
