### ISSUE TITLE
How to transfer uvs from source .objs onto poisson reconstruction model?

### ISSUE THREAD

**Issue by DanWhitton** [cnr-isti-vclab/meshlab#52]
I've been struggling for some time to find a way in Meshlab to include or transfer UV’s onto a poisson model from source meshes. I will try to explain more of what I’m trying to accomplish below.   
 
My source meshes have uv’s along with texture data. I need to build a fused model and include the texture data. It is for facial expression scan data reconstruction for a production pipeline which ultimately builds a facial rig for animation. Our source scan data includes marker information which we use to register, build a fused scan model which is used to generate a retopologized mesh for blendshapes.
 
Previously, we were using David3D. http://www.david-3d.com/en/support/downloads
David 3D used poisson surface reconstruction to create a fused model. The fused model it created brought along the uvs and optimized the source textures into 1 uv tile. I'll post a picture of the result below that I'm looking to recreate in MeshLab.
 
My need to find this solution in meshlab is to build tools to help automate this process. David3D version 5 does not have an development kit to program around.
 
Is it possible in Meshlab to apply the uvs from the regions used from the source mesh onto the poison model? Could I use a filter to transfer them? Reproject them?
![poisson_model_uv_layout](https://cloud.githubusercontent.com/assets/25106617/21938653/102e5bf6-d971-11e6-8379-2450f936778e.jpg)
 Or is there another reconstruction method/ process from within Meshlab that will keep the uv’s?
 
Here is an image of what the resulting uv parameter looks like from David. The uvs are white on the left half of the image. 
 
Please let me know if I need to be clearer in my explanation or if you need an example file.
 
Sincerely,

Dan Whitton

**Comment by mcallieri** [comment]
No, in MeshLab there is no direct way to transfer UV mapping between two layers. 
This is because UV transfer is not, in the general case, a trivial task. It is not simply a matter of assigning to the new surface the "closest" UV of the original mesh: this would not work on UV discontinuities, which are present in the example you linked. Additionally, the two meshes should be almost coincident, otherwise you would also have problems also in defining the "closest" UV.

There are a couple ways to do it, but require manual work and a re-sampling of the texture:
- create a UV mapping of the re-meshed model using whatever tool you may have, then resample the existing texture on the new parametrization using "transfer: vertex attributes to Texture (1 or 2 meshes)", using texture color as source
- load the original mesh, and using the screenshot function, create "virtual" photos of the model (turn off illumination and do NOT use ortho views), adding them as raster layers, until the model surface has been fully covered. Load the new model, that should be in the same space, and texture-map it using the "parametrization + texturing " using those registered images

In MeshLab it is also possible to create a new texture from the original images, if you have a way to import the registered cameras...

**Comment by cignoni** [comment]
Please DO NOT USE issues as a forum. 
For questions and other discussions please use stackoverflow
http://stackoverflow.com/questions/tagged/meshlab
