### ISSUE TITLE
g1 errors:  invalid frame buffer operation

### ISSUE THREAD

**Issue by jim27** [cnr-isti-vclab/meshlab#57]
I just started using Meshlab to view 3D scans; when I try to perform an operation such as simplifying, the operation is not allowed due to a "g1 error: invalid frame buffer operation".  What does this even mean?  I am not a programmer, I just want to use Meshlab to open, check out and simplify scans for transfer to a printer. Any ideas on how to fix this?  Mac  with NVIDIA GeForce GTX 675MX, running OS X 10.12.2

**Comment by granzuglia** [comment]
The "gl error: invalid frame buffer operation" in Mac OSx is caused by the internal implemantation of the Qt framework. It seems impossible to remove it but, as long as we know (and we have a long experience with this error message...) it doesn't cause any meaningful limitation to the use of MeshLab and the applicability of the filters on the loaded 3D models. Can you give us some additional info about your problems?

**Comment by jim27** [comment]
Dear Mr. Ranzuglia,

As a complete newcomer to the world of 3D mesh clouds, I am just trying to find my way through some simple tasks.  I have had several pieces scanned by a local company with the idea of eventually printing them using sls printing  technology.  If I send the files to a company such as Shapeways for printing, the files as I have them now are too large, i.e. too many faces.  Shapeways requires fewer than 1,000,000 faces, and I have several files three times that large.  I want to simplify the pieces, reducing the number of faces while retaining the surface texture. Every time I try to use one of the ’simplify’ commands in Meshlab, the piece becomes unrecognizable.  Can you tell me a way to reduce the number of faces on these pieces so that I can have them printed commercially?

Thank you for any help you can give me in this matter.

Sincerely, 
Linda Threadgill

**Comment by granzuglia** [comment]
Try "Filters->Remeshing, Simplification & Reconstruction->Simplification: Quadric Edge Collapse (with texture)" using the standard parameters on every single mesh composing your scene. In this way it will remove half of the faces from the model. You can apply it again on the resulting mesh if you want to simplify further. Let me know if you will have still problems.

**Comment by mcallieri** [comment]
can you post an image to show which kind of problems you have?

take a look at this videotutorial
https://www.youtube.com/watch?v=PWM6EGVVNQU

use "Filters->Remeshing, Simplification & Reconstruction->Simplification: Quadric Edge Collapse (with texture)" if you DO HAVE a texture, use "Filters->Remeshing, Simplification & Reconstruction->Simplification: Quadric Edge Collapse" otherwise.

Just enter the number of faces you need in the first parameter, and hit apply

Be sure you do not have duplicated vertices (each triangle is separated)... if so, use "remove duplicated vertices" before simplifying.

**Comment by jim27** [comment]
Thank you for getting back to me about my problem.  The simplification filter you suggested is working fine for what I need now.  I guess I was just using the wrong filter.

Thanks again!

**Comment by bplmpdc** [comment]
framebuffer operation
There are gl errors: invalid framebuffer operation

**Comment by jiapei100** [comment]
It seems this **There are gl errors: invalid framebuffer operation** error is still going on, from my side...
