### ISSUE TITLE
Export as Quads obj 

### ISSUE THREAD

**Issue by umarmuzammil** [cnr-isti-vclab/meshlab#597]
I know mesh lab internally works with triangles but when I turn my Triangulated mesh to pure quad Dominant using the filter and export it, it still exports as triangles. I cant seem to export Obj as quads. If meshlab cant export it, what would be the purpose of that filter ?

**Comment by alemuntoni** [comment]
Hi @umarmuzammil,
when saving as obj, you shoud check also the option "convert triangles to polygons". 
I agree that the GUI could be more clearer, since it asks to check two (pretty much identical) options to obtain the desired result.. I'll take care of this as soon as possible.
Thanks for reporting this!

**Comment by Kenzyyyy** [comment]
Meshlab server has same problem.  What kind of options should I specify to export the mesh with quad polygon as obj format?

**Comment by alemuntoni** [comment]
Fixed in previous commits. Now the obj exporter has a single option for polygonal meshes.
