### ISSUE TITLE
Screened Poisson crash MacOS app

### ISSUE THREAD

**Issue by enricobez** [cnr-isti-vclab/meshlab#617]
When I try to apply the "Remeshing Screened Poisson" filter, the app crashes instantly

**Comment by rpavlik** [comment]
What version of the app are you using?

**Comment by dharma77** [comment]
MeshLab_64bit_fp v2020.02   (built on Feb 12 2020)

**Comment by rpavlik** [comment]
I think this is probably the same bug as https://github.com/cnr-isti-vclab/meshlab/issues/598

**Comment by dharma77** [comment]
Yes I've read that but I still have the issue.

**Comment by bennniii** [comment]
same here with 2020.03 and 2020.04. here's my [crashreport](https://pastebin.com/stGJ4FA4)

**Comment by Benno92** [comment]
I have the same problem. did anyone find a solution?

**Comment by alemuntoni** [comment]
We noticed that the problem is related with the Apple sign and notarization process.
Any MeshLab that has not been signed works. 
[Here](https://github.com/cnr-isti-vclab/meshlab/actions?query=workflow%3ACompileMacOS) you can find the MacOS workflows, each of them produces a zip that contains a non-signed MeshLab dmg.

**Comment by alemuntoni** [comment]
I am closing this issue since it is a duplicate of #598
