### ISSUE TITLE
Importing FBX file crashes MeshLab

### ISSUE THREAD

**Issue by kaimikael** [cnr-isti-vclab/meshlab#619]
I run MeshLab 2020.02 under OS X 10.15.3.

I start MeshLab, and select File->Import Mesh… and attempt to import the attached FBX file.  MeshLab crashes immediately.
I attach the crash log.

[meshlab_2020-03-25-163151_Administrators-MacBook-Pro.crash.zip](https://github.com/cnr-isti-vclab/meshlab/files/4381855/meshlab_2020-03-25-163151_Administrators-MacBook-Pro.crash.zip)
[Brädspelsfigur.fbx.zip](https://github.com/cnr-isti-vclab/meshlab/files/4381856/Bradspelsfigur.fbx.zip)

**Comment by alemuntoni** [comment]
Hi @kaimikael, thanks for reporting. It was a bug in the fbx importer, fixed with the last commit.
Next MeshLab version (2020.04) will work.

**Comment by marcusx2** [comment]
It was not fixed at all. I can't import fbx files, it will consume all the RAM in my computer and BSOD it.

**Comment by Ph0t0nX** [comment]
I tried 4 different fbx files.  all of them say just show the vertexes and at the bottom it says "faces: 0".  Does it not supported fbx files that have bones and animations?

**Comment by alemuntoni** [comment]
@marcusx2 the particular issue reported here has been solved, and the attached file can be correctly imported in MeshLab.
You did not share any file, so I cannot test your particular case.

@Ph0t0nX it could be the case. FBX is a proprietary file format, therefore I cannot test any of these cases. Sharing some of these files may help on solving this issue.

**Comment by luizavolpi** [comment]
I'm having the same problem, although I am using Windows 11 and MeshLab version 2022.02 (I tried with the latest 2023 version, and also didn't work, so I decided to downgrade thinking maybe it was a bug in the newest version). I am unable to share the file here since even zipped it's larger than 25 MB. Could it be that it's crashing due to the size of the file? The same mesh in .obj opens fine, but I need the fbx one because it contains the texture also
