### ISSUE TITLE
Problem with the provided libmpir.a?

### ISSUE THREAD

**Issue by szyszkos** [cnr-isti-vclab/meshlab#74]
Compiling meshlab_full results in an abort with link failure and this message:

 error: ../../../src/external/lib/linux-g++/libmpir.a(lt4-clear.o): unrecognized relocation (0x2a) in section `.text'

**Comment by DBobkov** [comment]
Likely that your compiler differs from the standard one, thus you need to compile libmpir on your own. For more details see issue #47

**Comment by cignoni** [comment]
Agree, while for targeted osx releases it make sense to have binaries of libs, for linux it does not. We definitely need someone fully dedicated to maintain the linux distribution. 
Currently none of our core developers use linux as its main platform...
Any help is welcome.

**Comment by DBobkov** [comment]
I just put together a small script to make Meshlab 2016.2 on Linux Ubuntu distribution. I had issues with io_txt, mpir and plugins. Thus, I included all the issues and their fixes in the code. Tested on Ubuntu 14.04.5 64-bit with gcc-4.9. You are welcome to include this if you consider it worthy.


QT57_exec=<path-to-your-qt5.7-qmake>

# 1. vcglib
git clone https://github.com/cnr-isti-vclab/vcglib.git

# 2. meshlab
git clone https://github.com/cnr-isti-vclab/meshlab.git
cd meshlab
git checkout tags/v2016.12
cd src/external/
${QT57_exec} external.pro -o Makefile
make

# 3. now fix mpir issue
cd ../../../ # get out of the folder
wget http://mpir.org/mpir-2.4.0.tar.bz2
tar xjvf mpir-2.4.0.tar.bz2
cd mpir-2.4.0/
./configure --enable-cxx --enable-static --with-pic
make
cp .libs/libmpir*.a ../meshlab/src/external/lib/linux-g++/
cp mpir*.h ../meshlab/src/external/inc/linux-g++/mpir-2.4.0

# 4. now compile meshlab
cd ../meshlab/src
sed -i 's/io_TXT/io_txt/' meshlab_full.pro # there is an issue with io_TXT otherwise
mv plugins_experimental/io_TXT plugins_experimental/io_txt
${QT57_exec} meshlab_full.pro -o Makefile
# poisson filter enable (https://github.com/cnr-isti-vclab/meshlab/issues/44)
cp meshlabplugins/filter_measure/filter_measure.xml distrib/plugins/
cp meshlabplugins/filter_mutualinfoxml/filter_mutualinfo.xml distrib/plugins/
cp meshlabplugins/filter_screened_poisson/filter_screened_poisson.xml distrib/plugins/
make

**Comment by szyszkos** [comment]
Thank you very much!  I'll try this out on my 2 linux distributions (Debian and PCLinuxOS) at the earliest opportunity (next week) and report back.

**Comment by szyszkos** [comment]
Well, this does, in fact, work.
But I had to make a few tweaks:
I compiled with gcc-4.9.2. on a x86-64 PCLinuxOS distribution running the 4.7.5 kernel and Qt5.8. (I pointed {QT57_exec} to my Qt5.8 bin directory).

Compiling the meshlab externals worked fine but then could not at first compile mpir.

After replacing ./mpir-2.4.0/mpn/generic/preinv_divrem_1.c with ./mpir-2.4.0/tune/preinv_divrem_1.c, mpir compiled OK and created the needed .a and .h files, which I copied as described in step 3.

In step 4,  "mv plugins_experimental/io_TXT plugins_experimental/io_txt" failed due to file not found, so I skipped it and proceeded with step 4 and on through the following "poisson filter enable" steps to the make, which succeeded and generated a working Meshlab executable in Linux!  I will compare it to the windows version to check functionality and plugins, etc.

One other thing - during my initial attempt to compile 2 weeks ago, there were four functions in a switch which were failing.  For expediency and without trying to solve the problem, I simply changed the cases to execute functions that compiled.

In /meshlab/src/meshlabplugins/filter_meshing/meshfilter.cpp


Original code starting at line 1242:

		switch(par.getEnum("CurvColorMethod"))
		{
			case 0: tri::UpdateQuality<CMeshO>::VertexFromMeanCurvatureDir    (m.cm); break;
			case 1: tri::UpdateQuality<CMeshO>::VertexFromGaussianCurvatureDir(m.cm); break;
			case 2: tri::UpdateQuality<CMeshO>::VertexFromMinCurvatureDir(m.cm); break;
            case 3: tri::UpdateQuality<CMeshO>::VertexFromMaxCurvatureDir(m.cm); break;
            case 4: tri::UpdateQuality<CMeshO>::VertexFromShapeIndexCurvatureDir(m.cm); break;
            case 5: tri::UpdateQuality<CMeshO>::VertexFromCurvednessCurvatureDir(m.cm); break;
            case 6: tri::UpdateQuality<CMeshO>::VertexConstant(m.cm,0); break;          
}


My altered version:
		switch(par.getEnum("CurvColorMethod"))
		{
			case 0: tri::UpdateQuality<CMeshO>::VertexFromMeanCurvatureDir    (m.cm); break;
			case 1: tri::UpdateQuality<CMeshO>::VertexFromGaussianCurvatureDir(m.cm); break;
			case 2: tri::UpdateQuality<CMeshO>::**VertexFromMeanCurvatureDir**    (m.cm); break;
            case 3: tri::UpdateQuality<CMeshO>::**VertexConstant(m.cm,0)**; break;
            case 4: tri::UpdateQuality<CMeshO>::**VertexConstant(m.cm,0)**; break;
            case 5: tri::UpdateQuality<CMeshO>::**VertexConstant(m.cm,0)**; break;
            case 6: tri::UpdateQuality<CMeshO>::VertexConstant(m.cm,0); break;          
		}


Thanks again!

Steve

**Comment by cignoni** [comment]
Probably the compiling failure was due to using an updated version of the meshlab repo with a non-up-to-date version of the vcglib (devel branch) repo.
