### ISSUE TITLE
unexpected behavior: compute normals for point set  filter does not work correctly anymore.

### ISSUE THREAD

**Issue by MohamadZohoori** [cnr-isti-vclab/meshlab#749]
Hi,

I have been using meshlabserver for a year and have automated a number of filters one of which is: compute normals for point set.
The problem here is that not only doesn't this filter work correctly in meshlabserver, it does not work correctly either in meshlab software. The normals seem to be oriented towards stochastic directions and not outwards as it had always been. This problem has started for 2 weeks just the date when version 2020 was released. (weird, right?) BTW, I have never installed version 2020.
I will be so grateful if you help me solve this problem.

Thanks in advance for your help.

**Comment by GiovanniSer** [comment]
I had the same problem. In my case the problem is born due the last far numbers of the digits in the floating values.
I use CAD dwg and because MeshLab does not import DXF files, I write STL files using lisp from the CAD.
But the floating values are ever approximated, so if two faces with a common edges are rotated and translated in different ways, it is possible that in the dwg the last digits after the comma are different. If the digits after the comma are very many. So the common edges are no longer equal. And in MeshLab the face does not call near and does not normalize the other face.
I solved in output. I use only 7 digits after the comma, cutting away the most little decimals.
So MeshLab recognizes the common edges because they are equal for sure. I don't know if your problem is this, but I had the same bad result normalizing my shapes exactly and only with the new 2020 version.

**Comment by alemuntoni** [comment]
Could you please provide a minimal reproducible example?
- platform you experience the issue
- meshlab version (2020 is not enough: there are 7 2020 versions)
- a file where the issue happens

Btw, @MohamadZohoori: there is no way that the issue is related to a 2020 version if you never installed it.

**Comment by copyme** [comment]
@alemuntoni I have experienced this issue also here (Linux snap package with 2020.7). I have not tried yet with an older version of Meshlab but I plan to. @MohamadZohoori if you use a snap package then snapd is updating all the snaps each day automatically.
