### ISSUE TITLE
Crash from using Poisson reconstruction

### ISSUE THREAD

**Issue by embeh** [cnr-isti-vclab/meshlab#75]
This is using MeshLab_64bit_fp v2016.12 (as of Dec 23 2016) on Win7 Pro x64

Direct crash to desktop when using these steps:

1.) Filter > Create New Mesh Layer > Icosahedron
2.) Filter > Remeshing > Screened Poisson Surface Reconstruction > default params: depth=8, min no. of sample s= 1.5, weight = 4, all checkboxes off > Apply --> immediate crash

Same for other geometric primitives, such as sphere. Checking 'Pre-Clean' still results in a crash

**Comment by mcallieri** [comment]
The Poisson Filter needs to write some cache files in the "working" folder, i.e. the folder where the models have been imported. If you create a new layer, and do not save in a WRITABLE folder, the current working folder is still c:\program files\VCG\MeshLab, that is READ-ONLY.

In order to use the filter, you should load files from a location on your PC where you can read AND write.

If you try creating a new layer, save it on your desktop, and then alunch poisson, it should work.

The same problems happens if you try to launch poisson, or also VCG merging on one of the samples... as they are in a folder that is read-only, this will cause problems.

Sorry, we will add some info in the help, and will try to find a way to give an error, instead of creashing, but is not that easy...

**Comment by embeh** [comment]
Thanks! Here's what I tried: 

Create a sphere. export to d:\tmp\sphere.ply and run the Poisson filter -- same result, crash to desktop
Only after restarting ML and opening the same .ply from that location would the Poisson reconstruction not crash.

Also, it seems that the new Poisson reconstruction is a lot more demanding than the old one, too. Loading one of my previous 3D scanned meshes, I get many errors from the filter despite the 'Pre-Clean' option until I recompute the normals. This used to work just fine in older versions of MeshLab

**Comment by mcallieri** [comment]
Thanks, we will see to this... seems the current folder is not updated correctly :(

The pre-clean option is not working, at the moment. Sorry, our fault. We are fixing it.
However, the new poisson only require for ALL points to have a valid normal. For the rest, it does require less memory and is more CPU efficient (parallel).

**Comment by mcallieri** [comment]
I think I fixed it:
- now, if the folder is not writable, the filter will FAIL (and not crash), and an error message is shown in the log area
- when a new layer is saved, the current folder is updated.
We will test it and ship the update with the new release (around 1 month).
