### ISSUE TITLE
What is wedge about the parameter problem of "meshlab server"? How to translate?

### ISSUE THREAD

**Issue by weiyu666** [cnr-isti-vclab/meshlab#817]
Hello, I come to China~
        Regarding the question of "meshlab server" parameter "w" and "wedge", what does "wedge" refer to. I don't remember this, but there are such attributes as "wedge colors, wedge normals, wedge texture coords". I guess it is a quadrilateral mesh. ? But the face should include quadrilaterals and triangles! Although the triangle is more common...
![图片](https://user-images.githubusercontent.com/22174508/97412469-94327900-193c-11eb-9e30-6299d5e11d5a.png)
I also hope to get the answer~ 
@cignoni  @granzuglia @alemuntoni @mcallieri 
                                                            Thanks~

**Comment by NPatch** [comment]
Wedge usually means face. A vertex can be shared completely without duplication only if all attributes are per-vertex(due to how indexing works), meaning they have only one possible value for that vertex, no matter how many faces the vertex participates in. When you have different values for normals or uvs or colors , per-face, then they are called per-wedge attributes.

You can go to Filters->Texture->Convert Per-Wedge UVs to Per-Vertex UVs. You'll notice that the vertex count shoots up once you do that, because we are essentially duplicating the vertices(thus they are not shared anymore). So if a vertex was shared by 6 triangles before and had a different set of UVs for each of them, will now become 6 overlapping vertices with a single set of UVs participating in one triangle. The idea is similar to how you deal with indexed UVs in OBJ parsing.

**Comment by weiyu666** [comment]
Hello, thank you for your answer.
 I understand it in general. Understand that you said "Wedge usually means face" and the relationship with vertices (index relationship: no vertices are shared).
 Question 1: What is the difference between "face" and "Wedge" here?
Question 2: The ".xlm" script that uses xml format is essentially the algorithm tuning parameter set by the user? However, when you use the meshlab server, how to confirm the following parameters, such as the attributes of "face" and "Wedge", "fc", "wn", etc., because I want a ".xlm" script here and my own IO settings Its value is read in different 3D models, but the problem is how to determine the "vt", "fc" and so on in the command line? How to organize operations of different models but calling the same Filters algorithm? (Of course, I use the read "obj" format here, I only need to modify the value in the ".xlm" script to adjust the algorithm parameters) @NPatch

**Comment by NPatch** [comment]
Q1: Check Figure 3 and its caption [here](http://hhoppe.com/efficientpm.pdf).
Q2: I haven't used the server more than twice so I don't know if there is a way to automate this without dependencies.
But you can always fashion a command line app in some lang you feel comfy with which also allows you to write sth quick. You can parse OBJ or PLY and look for vt, fc and so on and then you can call the server inside the app with the arguments you want and bonus, you can also generate the mlx file youself since it's XML and therefore easily regenerated so you can add any dynamic parameters based on the file analysis.
I'd still wait for input from the people you tagged earlier in case there's some better way to use the server.

**Comment by weiyu666** [comment]
Thank you for your answer, I have benefited a lot, thank you @NPatch  ~

**Comment by alemuntoni** [comment]
Hi @weiyu666, I am really sorry for the late reply (I don't know why I am seeing this just now, maybe I lost the email).
About the Q2, I suggest to look into [pymeshlab](https://github.com/cnr-isti-vclab/PyMeshLab). It's definitely more dynamic than meshlabserver (that has been dismissed), and will allow you to change parameters on every call of any `apply_filter` function.

**Comment by NPatch** [comment]
Definitely more versatile choice than meshserver. Thanks!
