### ISSUE TITLE
Problem with scripted move selected faces to new layer

### ISSUE THREAD

**Issue by nyersa** [cnr-isti-vclab/meshlab#86]
I need to create a script that splits a mesh into two separate meshes based on normal orientation. I first perform a conditional face selection (fnz >= 0) and then try move selected faces to another layer. When performing this manually it works great, however when trying to save this as a script it does not work either through the GUI or manually. See attached screen shot for an example.

![split](https://cloud.githubusercontent.com/assets/3900770/23181685/c14ad928-f82a-11e6-80c7-1340d68e504e.png)

**Comment by mcallieri** [comment]
confirmed. We are searching.

**Comment by mcallieri** [comment]
the two issues seems related, there is a problem with filters scripts using selection. We are investigating.

**Comment by granzuglia** [comment]
It was not a bug. I'm quite sure you were not using the proper parameters for the command line. They are quite changed from the previous MeshLabServer version.
try something like:

meshlabserver -i C:\Users\ranzuglia\Desktop\tmp\oval.ply -w C:\Users\ranzuglia\Desktop\tmp\output.mlp -s C:\Users\ranzuglia\Desktop\tmp\movescript.mlx

It will load the ply file -> applying to it the movescript.mlx (containing the procedure you described) -> a output.mlp project will be generated. It will contain two (saved) layers: oval_out.ply and  SelectedFacesSubset_out.ply.

Please, let me know if you have still problems! Feel free to reopen a new ticket if you think that something is not working.

Anyway, as a general rule, I suggest to everyone to regenerate the scripted MeshLabServer files with the correspondent MeshLab version. The syntax of the scripting files may change among the different versions.

PS in the upcoming MeshLab release the MeshLabServer the semantics of parameters for saving files are slightly changed, in order to be more flexible and meaningful (hopefully).
