### ISSUE TITLE
Reload does not reload all meshes

### ISSUE THREAD

**Issue by christian-rauch** [cnr-isti-vclab/meshlab#904]
The `Reload` button in the top toolbar (symbol with two arrows) can be used to reload an open mesh. But this only applies to the currently selected (active) mesh. When multiple meshes are loaded this means that only one of them gets reloaded which might result in an inconsistent representation.

The `Reload` feature should reload all meshes in the current project.

Version: 2020.12 from binary distribution `MeshLab2020.12-linux.tar.gz`.

Edit: There is a `Reload All` (Ctrl + Shift + R) option in the `File` menu. Maybe this one should be the standard for the reload function in the toolbar.

**Comment by alemuntoni** [comment]
Mmh, I don't know if it would be a good idea to change behaviour of a commonly used button of the toolbar. 
The reload button exists since the first MeshLab version, and users could find this change unexpected.
A good idea could be to add a new button in the toolbar that runs the "Reload All" action.

**Comment by christian-rauch** [comment]
There could be two buttons. But it should be clear from the tooltip or the icon that one does only reload the active mesh and the other reloads all meshes.
