### ISSUE TITLE
Meshlab snap revision 6 does not exist anymore, meshlabserver not available

### ISSUE THREAD

**Issue by mantyni** [cnr-isti-vclab/meshlab#929]
Hello, 

I am working with snap meshlab package. 

I have system dependencies for meshlabserver that is supported in snap meshlab revision 6. 

But since yesterday snap revision 6 is not available anymore. Only revision 36 is available, which superseded meshlabserver with PyMeshLab and my systems are not compatible with it. 

`sudo snap list meshlab --all`
Name     Version  Rev  Tracking       Publisher       Notes
meshlab  2020.12  36   latest/stable  cnr-isti-vclab  -

Could the team please return snap meshlab package of revision 6 to give more time for transition to PyMeshlab from meshlab server? 

Thanks

**Comment by alemuntoni** [comment]
I am sorry but the availability of revision 6 was automatically removed by the snap store, and I am not going to return the snap package to an old version of meshlab (causing a downgrade to all the meshlab users). 
Since the snap store removed old versions, I think that the only way to install old snap versions is to manually download them from other sources. For example, you can find the snap package of 2020.09 in the relase page.
