### ISSUE TITLE
I create Flatpak for MeshLab

### ISSUE THREAD

**Issue by kevinsmia1939** [cnr-isti-vclab/meshlab#936]
Hi, I'm submitting MeshLab to Flathub, what do you think?

https://github.com/kevinsmia1939/flathub/tree/net.meshlab.MeshLab

Unfortunately, Wayland does not work, same issue as https://github.com/cnr-isti-vclab/meshlab/issues/738

**Comment by alemuntoni** [comment]
It's fine to me to have it also in flathub! I just don't know anything about how it works, therefore I cannot guarantee any support on issues that concerns flathub in particular...

**Comment by alemuntoni** [comment]
About wayland, it could be something related with glew (https://github.com/nigels-com/glew/issues/172)...

**Comment by kevinsmia1939** [comment]
Thanks will look into it.
I will have to refine sand box permission.
Just to make sure, does meshlab need network connection?
Does it need access to specific directory?
Right now, it can import and export file with "portal", which user see as "file selector dialog"

**Comment by alemuntoni** [comment]
> Just to make sure, does meshlab need network connection?

Meshlab uses network connection to check for updates, but it is not mandatory ho have it.

> Does it need access to specific directory?

It needs to access to the system default temporary directory.

> Do I need to install lib3ds, qhull, openCTM, etc? Because I see that vcglib include those already.

All these libraries are already bundled inside meshlab. However if these libraries are already installed in the system when building meshlab, the system ones are used. You can also choose which libraries use as system provided or bundled with the "ALLOW" options in the cmake configuration. If these libraries are available in some way with flatpak, it would be batter to use them and set as dipendencies, since the meshlab package would be lighter.

> Also, are there particular screenshot that you want to be presented? I just use screenshot from feature section at meshroom.net at the moment.

We actually should prepare some new screenshots of the application... At the moment I don't have good recent ones.

**Comment by kevinsmia1939** [comment]
@alemuntoni 

MeshLab now on Flathub.
Let me know what you think.
Thanks
https://flathub.org/apps/details/net.meshlab.MeshLab

**Comment by alemuntoni** [comment]
That's great @kevinsmia1939!! Thank you very much! :)
It's great to have multiple ways to get and install easily meshlab :)
Is it ok if I tag you wheter some issues related with the flathub package will be opened here?

**Comment by kevinsmia1939** [comment]
> That's great @kevinsmia1939!! Thank you very much! :)
> It's great to have multiple ways to get and install easily meshlab :)
> Is it ok if I tag you wheter some issues related with the flathub package will be opened here?

Sure thing.

**Comment by alemuntoni** [comment]
Great :) Thanks again!! :)
