### ISSUE TITLE
Can't save/export edited polygonal mesh!

### ISSUE THREAD

**Issue by Urbaxter** [cnr-isti-vclab/meshlab#946]
Hi guys,

I'm using Windows 10 and just installed MeshLab_64bit_fp v2020.12

I used the Filter->Polygonal and Quad Mesh-> Turn into Quad-Dominant mesh

So, I used it to turn the tris in quads in a simple mesh, and it works, BUT, every time I Export the edited mesh, the file exported keeps the same as when I imported, nothing change!
I tried to export in .stl, .obj, and also in other files but every time the result is the same, the exported mesh don't show any modification!

I'm trying to solve this for hours without any success, also did a search on YouTube, discussions and forums, but didn't find anything, very annoying!
Can you guys, please, tell me what's happening?

Thank you.
Best,
Urbano Rodriguez

**Comment by alemuntoni** [comment]
There was an issue regarding the export of polygonal meshes in the obj format. In 2020.12, you need to check both the checkboxes "polygonal" in the save dialog. Alternatively, you can download one of the last nightly versions like [this one](https://github.com/cnr-isti-vclab/meshlab/actions/runs/748680128), since the issue has been already solved.
For stl, meshlab does not allow to export polygonal meshes in that format.
