### ISSUE TITLE
[feature request] convert to nxs/nxz

### ISSUE THREAD

**Issue by virgilejarrige** [cnr-isti-vclab/meshlab#980]
Hello,

I know that there is a binary for windows that is available here http://vcg.isti.cnr.it/nexus/

But it would be so convenient if it was implemented in Meshlab.

Would that be possible to allow Meshlab to convert OBJ/PLY objects into NXS/NXZ?

Regards,

Virgile

**Comment by pr0m1th3as** [comment]
Hi all,

I agree, that would be fantastic a fantastic feature. Especially for non-windows people like myself.
Perhaps, in case it's any easier, it could be integrated in PyMeshlab, since meshlab is deprecated as far as I understand. Anyway, thank you people for all the great work {3DHOP included :+1:  } you are doing over there at VCL :1st_place_medal: 
Regards.
Andreas

**Comment by alemuntoni** [comment]
Hi, 
I think it would be possible, but it requires some work to build everything on all the platforms since the nexus source code is quite old (last commit dates back to 2013). Therefore I don't know when this feature will be available.

Btw @pr0m1th3as, meshlabserver is deprecated, but not meshlab :)  And when the feature will be available in meshlab, it will be automatically available also in pymeshlab :)

**Comment by pr0m1th3as** [comment]
Thanks for the update,

I thought nexus was still being developed or maintained at least since latest tag was on 17 Jun 2020. Anyway, my main interest is due to its utilization by 3DHOP for loading models. I know I could also load .ply on 3DHOP but there is concern about network resources and performance. It would be a great help to be able to easily export our models to .nxz for our online gallery with Meshlab, which I use anyway for downsampling and other stuff.

Great work once again!

Regards,
Andreas

**Comment by alemuntoni** [comment]
Small update: the NXS/NXZ exporter is almost ready and I am confident that it will be in the next meshlab version! :)

**Comment by virgilejarrige** [comment]
Wow! I wasn't expecting the feature to be available so fast! That's awesome! 

Thank you!

**Comment by pr0m1th3as** [comment]
This is great news!! Thank you very much for this feature! It saves a lot of hassle converting our 3d models to nxz for our online gallery. Cheers!!

Regards,
Andreas

**Comment by alemuntoni** [comment]
NXS/NXZ exporter is now part of meshlab!
You can test it by downloading one of the [last nightly builds](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version), and it will be available in the next version of meshlab. :)
Feel free to open a new issue if some features of the exporter do not work as expected!
